### ISSUE TITLE
TypeError prevents analyses from completing successfully

### ISSUE THREAD

**Issue by hackdna** [parklab/refinery-platform#1094]
Commit: f709e268db9f9968a0ba6242a8690ea916306546

### Steps to reproduce
Run a Refinery test workflow

### Observed behavior
Analysis succeeds in Galaxy but fails in Refinery. Relevant entries from Celery worker1 log:
```
2016-05-06 11:49:59 DEBUG    analysis_manager.tasks:329 get_galaxy_download_tasks() - Preparing to download analysis results from Galaxy
2016-05-06 11:50:00 INFO     file_store.tasks:40 create() - Creating FileStoreItem using source 'http://192.168.50.1:8080/datasets/cbbbf59e8f08c98c/display?to_ext=txt'
2016-05-06 11:50:00 INFO     file_store:375 set_filetype() - File type is set to 'txt'
2016-05-06 11:50:00 INFO     file_store.tasks:49 create() - FileStoreItem created with UUID b23186f1-5585-4fc7-b973-da0c16d51591
2016-05-06 11:50:00 INFO     analysis_manager.tasks:167 run_analysis() - Starting downloading of results from Galaxy for analysis 'Test workflow: 5 steps without branching 2016-5-6@11:49:28 - guest - None provided.'
2016-05-06 11:50:05 INFO     core.models:1298 attach_outputs_dataset() - Results for '0eb5f5c3-ac17-489a-a95a-4f0ec65c7275' and output_file.txt: 1
2016-05-06 11:50:05 DEBUG    core.models:1318 attach_outputs_dataset() - Output file 1_test tool out.txt ('b23186f1-5585-4fc7-b973-da0c16d51591') assigned to node 1_test tool out ('0eaab2fe-cbc6-4dc6-83ec-3b7f1d46d274')
2016-05-06 11:50:05 INFO     core.models:1298 attach_outputs_dataset() - Results for '0eb5f5c3-ac17-489a-a95a-4f0ec65c7275' and output_file.txt: 0
2016-05-06 11:50:05 INFO     core.models:1307 attach_outputs_dataset() - No output file found for node 'output_file' ('2f94bfe6-1e75-42e2-bf54-0451b29ca449')
2016-05-06 11:50:05 INFO     core.models:1298 attach_outputs_dataset() - Results for '0eb5f5c3-ac17-489a-a95a-4f0ec65c7275' and output_file.txt: 0
2016-05-06 11:50:05 INFO     core.models:1307 attach_outputs_dataset() - No output file found for node 'output_file' ('cc958125-17e5-4b48-b582-43f81e3148a2')
2016-05-06 11:50:05 INFO     core.models:1298 attach_outputs_dataset() - Results for '0eb5f5c3-ac17-489a-a95a-4f0ec65c7275' and output_file.txt: 0
2016-05-06 11:50:05 INFO     core.models:1307 attach_outputs_dataset() - No output file found for node 'output_file' ('4269ef0a-01a2-4a6f-9d07-b95686e63f29')
2016-05-06 11:50:05 INFO     core.models:1298 attach_outputs_dataset() - Results for '0eb5f5c3-ac17-489a-a95a-4f0ec65c7275' and output_file.txt: 0
2016-05-06 11:50:05 INFO     core.models:1307 attach_outputs_dataset() - No output file found for node 'output_file' ('8205a1be-0280-4461-9f78-28f78c6ce321')
2016-05-06 11:50:05 INFO     data_set_manager.utils:430 _add_annotated_nodes() - 239 retrieved from data set
2016-05-06 11:50:05 INFO     data_set_manager.utils:468 _add_annotated_nodes() - 4 annotated nodes generated in 0.00597095489502
2016-05-06 11:50:05 INFO     data_set_manager.utils:493 _index_annotated_nodes() - 1 nodes for indexing
2016-05-06 11:50:06 INFO     data_set_manager.utils:502 _index_annotated_nodes() - 1 nodes indexed in 0.365716934204
2016-05-06 11:50:06 DEBUG    core.models:1203 rename_results() - Renaming analysis results
2016-05-06 11:50:06 DEBUG    file_store:442 rename_datafile() - Renaming datafile 7d/3f/display_bdfrACt to 1_test tool out.txt
2016-05-06 11:50:06 DEBUG    file_store:680 _rename_file_on_disk() - Renamed /vagrant/media/file_store/7d/3f/display_bdfrACt to /vagrant/media/file_store/ff/4c/1_test tool out_IK01mgJ.txt
2016-05-06 11:50:06 INFO     file_store:457 rename_datafile() - Datafile renamed
2016-05-06 11:50:06 INFO     analysis_manager.tasks:203 run_analysis() - Analysis 'Test workflow: 5 steps without branching 2016-5-6@11:49:28 - guest - None provided.' finished successfully
2016-05-06 11:50:06 ERROR    file_store:585 get_file_size() - FileStoreItem with UUID 27f9725f-3977-4a5e-a3ed-302984effaf9 does not exist
2016-05-06 11:50:06 ERROR    analysis_manager.tasks:37 on_failure() - Monitoring task for analysis with UUID '0eb5f5c3-ac17-489a-a95a-4f0ec65c7275' failed due to unexpected error: '<type 'exceptions.TypeError'>: unsupported operand type(s) for +=: 'int' and 'NoneType''
2016-05-06 11:50:06 ERROR    analysis_manager.tasks:44 on_failure() - Setting status of analysis 'Test workflow: 5 steps without branching 2016-5-6@11:49:28 - guest - None provided.' to failure
[2016-05-06 11:50:06,579: ERROR/MainProcess] Task analysis_manager.tasks.run_analysis[746a134c-e6c5-432c-ab1b-f461e3ea865d] raised unexpected: TypeError("unsupported operand type(s) for +=: 'int' and 'NoneType'",)
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/vagrant/refinery/analysis_manager/tasks.py", line 211, in run_analysis
    analysis.data_set.file_size = analysis.data_set.get_file_size()
  File "/vagrant/refinery/core/models.py", line 614, in get_file_size
    file_size += size
TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'
```

### Expected behavior
Analysis should complete successfully.

### Notes
`analysis.data_set.file_size = analysis.data_set.get_file_size()` was introduced in https://github.com/parklab/refinery-platform/commit/9d6ccbc0ddbe3adc3fac86253ed78b8d00d37433#diff-49577ffb85a5a9e95447df9c8ccc34ee

**Comment by flekschas** [comment]
I think `get_file_size` is not the root cause of this issue. In order to test whether `get_file_size` works correctly I ran a bunch of test workflows successfully and the file size got updated just fine.

**Comment by flekschas** [comment]
I've tested the _Test workflow: 5 steps without branching testing_ workflow on _Request for Comments (RFC) Test_ file _rfc125.txt_ without any problem and with line 218 uncommented. Commit d5f6aa559d2138c57409f75a9636aa888b7e669a

**Comment by hackdna** [comment]
Yes, I was running the same test workflow: https://github.com/refinery-platform/galaxy-tools/blob/develop/refinery_test_workflows/Test_workflow__5_steps_without_branching.ga

**Comment by flekschas** [comment]
That's weird. Did you ran things locally or on AWS?

Maybe @scottx611x can give this a try as well to see if someone else can reproduce the error.

**Comment by scottx611x** [comment]
@flekschas Sure not a problem. Am I testing this with @hackdna's change here: 0ad339a or without?

**Comment by flekschas** [comment]
@scottx611x Thanks! To check if you can reproduce the error you would have to revert 0ad339ac68154051e5af052803f487b05c6789de, i.e. uncomment that line.

**Comment by scottx611x** [comment]
@flekschas @hackdna I'm guessing this has something due to the reverted code I introduced. I'm running analyses in my galaxy_large_file_uploads branch with all of the reverted code fixed and things are working fine. Also have @hackdna's comment undone and the dataset's file_size is getting updated properly.
