### ISSUE TITLE
Can't import the massive dataset

### ISSUE THREAD

**Issue by scottx611x** [parklab/refinery-platform#1233]
Commit: 5388f2d86963aace2c06c9a82752fabbca021f83

### Steps to reproduce
1. Try and upload this dataset: 
[isa_11445_847064_2.zip](https://github.com/parklab/refinery-platform/files/357509/isa_11445_847064_2.zip)

### Observed behavior
The dataset upload will "spin" for about 5 mins and then error out.

It seems to be due to the celery worker getting lost/timing out.

#### Relevant logs:
---
**refinery.log**
```
2016-07-11 11:58:09 ERROR    django.request:224 handle_uncaught_exception() - Internal Server Error: /data_set_manager/import/isa-tab-form/
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)
  File "/vagrant/refinery/data_set_manager/views.py", line 286, in post
    response['data']['temp_file_path']
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/celery/result.py", line 175, in get
    raise meta['result']
WorkerLostError: Worker exited prematurely: signal 11 (SIGSEGV).
Internal Server Error: /data_set_manager/import/isa-tab-form/
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)
  File "/vagrant/refinery/data_set_manager/views.py", line 286, in post
    response['data']['temp_file_path']
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/celery/result.py", line 175, in get
    raise meta['result']
WorkerLostError: Worker exited prematurely: signal 11 (SIGSEGV).
2016-07-11 11:58:09 ERROR    django.request:224 handle_uncaught_exception() - Internal Server Error: /data_set_manager/import/isa-tab-form/
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)
  File "/vagrant/refinery/data_set_manager/views.py", line 286, in post
    response['data']['temp_file_path']
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/celery/result.py", line 175, in get
    raise meta['result']
WorkerLostError: Worker exited prematurely: signal 11 (SIGSEGV).
[11/Jul/2016 11:58:09] "POST /data_set_manager/import/isa-tab-form/ HTTP/1.1" 500 17936
```
### Expected behavior
This upload will take a long time generally, but it should still work.

**Comment by hackdna** [comment]
Could it be running out of memory?

**Comment by scottx611x** [comment]
@hackdna potentially, I'll try again and monitor that 👍

**Comment by scottx611x** [comment]
bumping `v.memory` to `4096` in my `Vagrantfile`allowed for this DS to import properly

@jkmarx  ^^^^^^
