### ISSUE TITLE
Inconsistent UI behavior and server error when canceling group creation

### ISSUE THREAD

**Issue by hackdna** [parklab/refinery-platform#1248]
Commit: ec43d5ba6d2f6cd5efcd583c9f420c11a4d5f548

### Steps to reproduce
1. Click on Collaboration link
1. Click on the + sign to open group creation dialog box
1. Click on the Cancel button in the dialog box

### Observed behavior
* Modal dialog with the message "Group Name cannot be left blank - try a different name." is displayed
* Internal server error logged:
```
Traceback (most recent call last):

  File "/home/ubuntu/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/tastypie/resources.py", line 202, in wrapper
    response = callback(request, *args, **kwargs)

  File "/home/ubuntu/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/tastypie/resources.py", line 433, in dispatch_list
    return self.dispatch('list', request, **kwargs)

  File "/home/ubuntu/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/tastypie/resources.py", line 465, in dispatch
    response = method(request, **kwargs)

  File "/home/ubuntu/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/tastypie/resources.py", line 1341, in post_list
    updated_bundle = self.obj_create(bundle, **self.remove_api_resource_names(kwargs))

  File "/srv/refinery-platform/refinery/core/api.py", line 1944, in obj_create
    new_ext_group.user_set.add(user)

  File "/home/ubuntu/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/db/models/fields/related.py", line 773, in __get__
    through=self.related.field.rel.through,

  File "/home/ubuntu/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/db/models/fields/related.py", line 524, in __init__
    (instance, source_field_name))

ValueError: "<ExtendedGroup: >" needs to have a value for field "group" before this many-to-many relationship can be used.
```

### Expected behavior
* No messages
* No internal server error

**Comment by mccalluc** [comment]
Note: if you *do* provide a name and then hit cancel, it does create a new group; ie, the handling of a blank name is correct, I think, but the cancel button seems to do the same thing as "Create Group"

**Comment by hackdna** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;cos9jM49&#x2F;304-data-set-sharing-collaboration"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> data set sharing &#x2F; collaboration</a>
