### ISSUE TITLE
How Should unknown FileTypes/FileExtensions be handled?

### ISSUE THREAD

**Issue by scottx611x** [parklab/refinery-platform#1258]
The behavior before commit: f05c3154c68dcc5be7c3895b5ca08c99a6beae3d included an `UNKNOWN` `FileType` and `FileExtension` that would be assigned to a file if we could not parse its extension properly.

It seems that the FileType column in the file browser doesn't get populated properly if all files that are part of a DataSet have file extensions unknown to Refinery. 

We could either re-add the afforementioned functionality or try to dynamically add new FileExtentions/FileTypes when we see them.... 

---

@hackdna: I know you had an opinion on why the `UNKNOWN` filetype should get removed, could you comment here?

@ngehlenborg Thoughts?

**Comment by hackdna** [comment]
Having an explicit UNKNOWN file type is redundant. If the type of some file is not known then simply don't assign one. It also makes Refinery tightly coupled to file type data that may or may not exist at run time.

Could you explain what happens in the file browser exactly and provide references to the relevant code?

**Comment by scottx611x** [comment]
@hackdna Basically if all files in a dataset have a file extension that Refinery doesn't know about then there will be no FileType column in the File Browser. 

Where we used to set the UNKNOWN filetype was here: https://github.com/parklab/refinery-platform/blob/develop/refinery/file_store/models.py#L372

As for the front end and why the FileType column is non-existent I believe Jennifer could elaborate...

@jkmarx Could you comment on this?

**Comment by jkmarx** [comment]
@sjhosui This was the issue Shannon came across when the file type was an extension which was not in the default list. The specific example was the Mov10_full_meta.txt file which has nodes with the extension fq. 

The issue is the front end does not receive file types as an attribute or any notification the file-type extension is unknown. An unknown state would be better than no state. The front end could accommodate it with a warning tooltip, so the user could notify their admin.

**Comment by jkmarx** [comment]
"The issue is the front end does not receive file types as an attribute or any notification the file-type extension is unknown. An unknown state would be better than no state. "

@scottx611x Did we convert this to an issue? It'd be preferred to have the API handle it. Let me know if this is feasible.

**Comment by scottx611x** [comment]
- [ ] Figure out what is returned from solr when fies have no associated filetype.

**Comment by scottx611x** [comment]
Just saw this when an unknown Filetype came back from a workflow:
```
[2017-11-21 15:45:23,398: ERROR/MainProcess] Task analysis_manager.tasks.run_analysis[fe40f449-aed8-431a-a90d-402d0e6ca0ea] raised unexpected: AttributeError("'NoneType' object has no attribute 'used_for_visualization'",)
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/ubuntu/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/srv/refinery-platform/refinery/analysis_manager/tasks.py", line 309, in run_analysis
    _attach_workflow_outputs(analysis_uuid)
  File "/srv/refinery-platform/refinery/analysis_manager/tasks.py", line 151, in _attach_workflow_outputs
    analysis.attach_outputs_dataset()
  File "/srv/refinery-platform/refinery/core/models.py", line 1657, in attach_outputs_dataset
    self._prepare_annotated_nodes(node_uuids)
  File "/srv/refinery-platform/refinery/core/models.py", line 1713, in _prepare_annotated_nodes
    self.rename_results()
  File "/srv/refinery-platform/refinery/core/models.py", line 1517, in rename_results
    node.run_generate_auxiliary_node_task()
```

**Comment by gmnelson** [comment]
Related to now-closed #2840, it's possible that files with unsupported file extensions do not import successfully (i.e. they do not become available for download via the File Browser). Now that I'm aware of this, the import issue is very avoidable -- just commenting to further inform this discussion of handling unknown file extensions.
