### ISSUE TITLE
tabular meta data file upload failing in Safari 10.0.0

### ISSUE THREAD

**Issue by ngehlenborg** [parklab/refinery-platform#1465]
* Specific code commit: fad81a20e6ce1334cde6c3350a1bf89fa4b82a81
* Version of the web browser and OS: Safari 10.0.0 on Mac OS X 10.12
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): https://test.stemcellcommons.org

### Steps to reproduce
Please list all the actions and the input data used:

1. Used sample data set (https://test.stemcellcommons.org/static/sample-files/refinery-sample-metadata.tsv)
2. Used default selection on upload page and clicked "Upload Dataset".

### Observed behavior
* Upload failed immediately with 500 server response.

### Expected behavior
* Data gets created.

It appears that this is a problem with Safari 10.0.0. The MIME type for the `POST` request is `text/html` whereas in Safari 9.1.3 the MIME type is `application/json`.

Safari 10.0.0 on Mac OS X 10.12:

![screen shot 2016-10-12 at 11 02 54 am](https://cloud.githubusercontent.com/assets/1216518/19315657/8701cd92-906c-11e6-95ba-ed7836d9c82c.png)

Safari 9.1.3 on Mac OS X 10.11.6:

<img width="1023" alt="good-safari" src="https://cloud.githubusercontent.com/assets/1216518/19315667/94c795ba-906c-11e6-8f85-79ab7b7eff6d.png">

<img width="440" alt="screen shot 2016-10-12 at 11 12 02 am" src="https://cloud.githubusercontent.com/assets/1216518/19315740/daded3ce-906c-11e6-9b32-8337e6c86e1a.png">

**Comment by hackdna** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [make sure error_msg in ProcessMetadataTableView.post() is JSON serializable](https://trello.com/c/j4ROZlE1/322-make-sure-error-msg-in-processmetadatatableview-post-is-json-serializable)

**Comment by ngehlenborg** [comment]
@scottx611x is able to reproduce this using Safari 10.0.0 on Mac OS X 10.10.5.

**Comment by hackdna** [comment]
Relevant Django errors (with sensitive information removed):
```
Traceback (most recent call last):

  File "/home/ubuntu/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/home/ubuntu/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)

  File "/home/ubuntu/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)

  File "/home/ubuntu/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)

  File "/srv/refinery-platform/refinery/data_set_manager/views.py", line 479, in post
    json.dumps({'error': error_msg}), 'application/json'

  File "/usr/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)

  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)

  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)

  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")

TypeError: IndexError('list index out of range',) is not JSON serializable

<WSGIRequest
path:/data_set_manager/import/metadata-table-form/,
GET:<QueryDict: {}>,
POST:<QueryDict: {u'data_file_column': [u'1'], u'species_column': [u'MOVexpr'], u'delimiter': [u'tab'], u'source_column_index': [u'0'], u'title': [u'Mov10_full_meta (1) with tabs']}>,
COOKIES:{'_ga': 'GA1.2.1149280071.1461676876',
'isa_tab_url': 'https://test.stemcellcommons.org/media/file_store/0b/26/filetypes.zip'},
META:{'CONTENT_LENGTH': '245310',
'CONTENT_TYPE': 'multipart/form-data; boundary=----WebKitFormBoundaryUz3rXXoAUYyRPNwm',
'CONTEXT_DOCUMENT_ROOT': '/var/www',
'CONTEXT_PREFIX': '',
'DJANGO_SETTINGS_MODULE': 'config.settings.aws',
'DOCUMENT_ROOT': '/var/www',
'GATEWAY_INTERFACE': 'CGI/1.1',
'HTTP_ACCEPT': 'application/json, text/plain, */*',
'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br',
'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.8',
'HTTP_CONNECTION': 'keep-alive',
'HTTP_COOKIE': '_ga=GA1.2.1149280071.1461676876; isa_tab_url="https://test.stemcellcommons.org/media/file_store/0b/26/filetypes.zip"; 'HTTP_HOST': 'test.stemcellcommons.org',
'HTTP_ORIGIN': 'https://test.stemcellcommons.org',
'HTTP_REFERER': 'https://test.stemcellcommons.org/data_set_manager/import/',
'HTTP_USER_AGENT': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36',
'HTTP_X_FORWARDED_FOR': '209.6.122.26',
'HTTP_X_FORWARDED_PORT': '443',
'HTTP_X_FORWARDED_PROTO': 'https',
'HTTP_X_REQUESTED_WITH': 'XMLHttpRequest',
'PATH_INFO': u'/data_set_manager/import/metadata-table-form/',
'PATH_TRANSLATED': '/srv/refinery-platform/refinery/config/wsgi.py/data_set_manager/import/metadata-table-form/',
'QUERY_STRING': '',
'REMOTE_ADDR': '172.31.39.215',
'REMOTE_PORT': '18877',
'REQUEST_METHOD': 'POST',
'REQUEST_SCHEME': 'http',
'REQUEST_URI': '/data_set_manager/import/metadata-table-form/',
'SCRIPT_FILENAME': '/srv/refinery-platform/refinery/config/wsgi.py',
'SCRIPT_NAME': u'',
'SCRIPT_URI': 'http://test.stemcellcommons.org/data_set_manager/import/metadata-table-form/',
'SCRIPT_URL': '/data_set_manager/import/metadata-table-form/',
'SERVER_ADDR': '172.31.40.244',
'SERVER_ADMIN': '[no address given]',
'SERVER_NAME': 'test.stemcellcommons.org',
'SERVER_PORT': '80',
'SERVER_PROTOCOL': 'HTTP/1.1',
'SERVER_SIGNATURE': '<address>Apache/2.4.7 (Ubuntu) Server at test.stemcellcommons.org Port 80</address>\n',
'SERVER_SOFTWARE': 'Apache/2.4.7 (Ubuntu)',
'mod_wsgi.application_group': 'test.stemcellcommons.org|',
'mod_wsgi.callable_object': 'application',
'mod_wsgi.enable_sendfile': '0',
'mod_wsgi.handler_script': '',
'mod_wsgi.input_chunked': '0',
'mod_wsgi.listener_host': '',
'mod_wsgi.listener_port': '80',
'mod_wsgi.process_group': 'refinery',
'mod_wsgi.queue_start': '1475873591601626',
'mod_wsgi.request_handler': 'wsgi-script',
'mod_wsgi.script_reloading': '1',
'mod_wsgi.version': (3, 4),
'wsgi.errors': <mod_wsgi.Log object at 0x7f870b579970>,
'wsgi.file_wrapper': <built-in method file_wrapper of mod_wsgi.Adapter object at 0x7f87282a0dc8>,
'wsgi.input': <mod_wsgi.Input object at 0x7f870b587b70>,
'wsgi.multiprocess': False,
'wsgi.multithread': True,
'wsgi.run_once': False,
'wsgi.url_scheme': 'http',
'wsgi.version': (1, 0)}>


Traceback (most recent call last):

  File "/home/ubuntu/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/home/ubuntu/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)

  File "/home/ubuntu/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)

  File "/home/ubuntu/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)

  File "/srv/refinery-platform/refinery/data_set_manager/views.py", line 479, in post
    json.dumps({'error': error_msg}), 'application/json'

  File "/usr/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)

  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)

  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)

  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")

TypeError: StopIteration() is not JSON serializable

<WSGIRequest
path:/data_set_manager/import/metadata-table-form/,
GET:<QueryDict: {}>,
POST:<QueryDict: {u'data_file_column': [u'2'], u'species_column': [u'species'], u'delimiter': [u'comma'], u'source_column_index': [u'0'], u'title': [u'same-file-different-species']}>,
COOKIES:{'_ga': 'GA1.2.2022625330.1441735527'},
META:{'CONTENT_LENGTH': '744',
'CONTENT_TYPE': 'multipart/form-data; boundary=----WebKitFormBoundary3mBQbdM1Lu1B1UyH',
'CONTEXT_DOCUMENT_ROOT': '/var/www',
'CONTEXT_PREFIX': '',
'DJANGO_SETTINGS_MODULE': 'config.settings.aws',
'DOCUMENT_ROOT': '/var/www',
'GATEWAY_INTERFACE': 'CGI/1.1',
'HTTP_ACCEPT': 'application/json, text/plain, */*',
'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
'HTTP_ACCEPT_LANGUAGE': 'en-us',
'HTTP_CONNECTION': 'keep-alive',
_ga=GA1.2.2022625330.1441735527',
'HTTP_DNT': '1',
'HTTP_HOST': 'test.stemcellcommons.org',
'HTTP_ORIGIN': 'https://test.stemcellcommons.org',
'HTTP_REFERER': 'https://test.stemcellcommons.org/data_set_manager/import/',
'HTTP_USER_AGENT': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12) AppleWebKit/602.1.50 (KHTML, like Gecko) Version/10.0 Safari/602.1.50',
'HTTP_X_FORWARDED_FOR': '134.174.140.208',
'HTTP_X_FORWARDED_PORT': '443',
'HTTP_X_FORWARDED_PROTO': 'https',
'HTTP_X_REQUESTED_WITH': 'XMLHttpRequest',
'PATH_INFO': u'/data_set_manager/import/metadata-table-form/',
'PATH_TRANSLATED': '/srv/refinery-platform/refinery/config/wsgi.py/data_set_manager/import/metadata-table-form/',
'QUERY_STRING': '',
'REMOTE_ADDR': '172.31.46.32',
'REMOTE_PORT': '23018',
'REQUEST_METHOD': 'POST',
'REQUEST_SCHEME': 'http',
'REQUEST_URI': '/data_set_manager/import/metadata-table-form/',
'SCRIPT_FILENAME': '/srv/refinery-platform/refinery/config/wsgi.py',
'SCRIPT_NAME': u'',
'SCRIPT_URI': 'http://test.stemcellcommons.org/data_set_manager/import/metadata-table-form/',
'SCRIPT_URL': '/data_set_manager/import/metadata-table-form/',
'SERVER_ADDR': '172.31.40.244',
'SERVER_ADMIN': '[no address given]',
'SERVER_NAME': 'test.stemcellcommons.org',
'SERVER_PORT': '80',
'SERVER_PROTOCOL': 'HTTP/1.1',
'SERVER_SIGNATURE': '<address>Apache/2.4.7 (Ubuntu) Server at test.stemcellcommons.org Port 80</address>\n',
'SERVER_SOFTWARE': 'Apache/2.4.7 (Ubuntu)',
'mod_wsgi.application_group': 'test.stemcellcommons.org|',
'mod_wsgi.callable_object': 'application',
'mod_wsgi.enable_sendfile': '0',
'mod_wsgi.handler_script': '',
'mod_wsgi.input_chunked': '0',
'mod_wsgi.listener_host': '',
'mod_wsgi.listener_port': '80',
'mod_wsgi.process_group': 'refinery',
'mod_wsgi.queue_start': '1476282559524952',
'mod_wsgi.request_handler': 'wsgi-script',
'mod_wsgi.script_reloading': '1',
'mod_wsgi.version': (3, 4),
'wsgi.errors': <mod_wsgi.Log object at 0x7f870f297170>,
'wsgi.file_wrapper': <built-in method file_wrapper of mod_wsgi.Adapter object at 0x7f872852aeb8>,
'wsgi.input': <mod_wsgi.Input object at 0x7f870f297430>,
'wsgi.multiprocess': False,
'wsgi.multithread': True,
'wsgi.run_once': False,
'wsgi.url_scheme': 'http',
'wsgi.version': (1, 0)}>
```
