### ISSUE TITLE
Unable to configure IGV for the selected file set.

### ISSUE THREAD

**Issue by hackdna** [parklab/refinery-platform#396]
Run a peak calling workflow, select Visualize tab and a TDF file.  Error message is shown, Launch IGV button is disabled.

Browser console:
```
Failed to load resource: the server responded with a status of 500 (INTERNAL SERVER ERROR) https://refinery-dev.stemcellcommons.org/solr/igv/
Error creating IGV session URLs. (error status 500)
```
Refinery log:
```
2014-03-11 14:08:16 DEBUG    views get_solr_results: core.views: get_solr_results
2014-03-11 14:08:16 DEBUG    views get_solr_results: core.views: get_solr_results
2014-03-11 14:08:17 WARNING  models get_item: _FileServerItem with data_file UUID 'None' does not exist
2014-03-11 14:08:17 ERROR    base handle_uncaught_exception: Internal Server Error: /solr/igv/
Traceback (most recent call last):
  File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/srv/scc/apps/refinery-platform/refinery/core/views.py", line 865, in solr_igv
    session_urls = igv_multi_species(solr_results, solr_annot)
  File "/srv/scc/apps/refinery-platform/refinery/visualization_manager/views.py", line 206, in igv_multi_species
    sampleFile = addIGVSamples(fields, unique_species[k]['solr'], unique_annot[k]['solr'])
  File "/srv/scc/apps/refinery-platform/refinery/visualization_manager/views.py", line 488, in addIGVSamples
    pheno_results = get_sample_lines(fields_dict, results_samp)
  File "/srv/scc/apps/refinery-platform/refinery/visualization_manager/views.py", line 584, in get_sample_lines
    line, url = get_file_name(row["uuid"], sampFile=True)
  File "/srv/scc/apps/refinery-platform/refinery/visualization_manager/views.py", line 548, in get_file_name
    temp_fs = FileStoreItem.objects.get(uuid=curr_file_uuid)
  File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/django/db/models/manager.py", line 143, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/django/db/models/query.py", line 404, in get
    self.model._meta.object_name)
DoesNotExist: FileStoreItem matching query does not exist.
```

**Comment by flekschas** [comment]
Which workflow generates a TDF file?

**Comment by flekschas** [comment]
I ran the "TF ChIP-Seq analysis using MACS2: hg19". It doesn't generate any TDF file and the other three ChiP-Seq workflows only differ in the species, so subsequently we cannot reproduce this error.
