### ISSUE TITLE
Duplicate base resource slugs are possible

### ISSUE THREAD

**Issue by ngehlenborg** [parklab/refinery-platform#4]
The slugs are not enforced to be unique.

**Comment by scottx611x** [comment]
@ngehlenborg Is this fix as simple as:

 ```diff
- slug = models.CharField(max_length=250, blank=True, null=True)
+ slug = models.CharField(unique=True, max_length=250, blank=True, null=True)
```

Or should I be delving deeper into this?

It seems like the behavior that you want has been implemented, shown below.

![screen shot 2015-09-22 at 2 24 56 pm](https://cloud.githubusercontent.com/assets/5629547/10027613/ff1b2ba0-6135-11e5-8190-8425cf877965.png)

**Comment by hackdna** [comment]
Yes, the solution is more involved that just adding a constraint to the model field. We need to handle duplicate slug error whenever a data set is saved. See this traceback for more details:
```
Traceback (most recent call last):

  File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)

  File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 25, in _wrapped_view
    return view_func(request, *args, **kwargs)

  File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)

  File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/django/views/generic/base.py", line 86, in dispatch
    return handler(request, *args, **kwargs)

  File "/srv/scc/apps/refinery-platform/refinery/data_set_manager/views.py", line 261, in post
    is_public=request.POST.get('is_public', False))

  File "/srv/scc/apps/refinery-platform/refinery/data_set_manager/single_file_column_parser.py", line 349, in process_metadata_table
    dataset_name=title, slug=slug, public=is_public)

  File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/celery/app/task/__init__.py", line 247, in __call__
    return self.run(*args, **kwargs)

  File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/celery/app/__init__.py", line 175, in run
    return fun(*args, **kwargs)

  File "/srv/scc/apps/refinery-platform/refinery/data_set_manager/tasks.py", line 364, in create_dataset
    dataset.save()

  File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/django/db/models/base.py", line 546, in save
    force_update=force_update, update_fields=update_fields)

  File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/django/db/models/base.py", line 626, in save_base
    rows = manager.using(using).filter(pk=pk_val)._update(values)

  File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/django/db/models/query.py", line 605, in _update
    return query.get_compiler(self.db).execute_sql(None)

  File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1014, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)

  File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)

  File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 56, in execute
    six.reraise(utils.IntegrityError, utils.IntegrityError(*tuple(e.args)), sys.exc_info()[2])

  File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 54, in execute
    return self.cursor.execute(query, args)

IntegrityError: duplicate key value violates unique constraint "core_dataset_slug_uniq"
```

**Comment by scottx611x** [comment]
@hackdna Thanks for looking into this
