### ISSUE TITLE
HTTP error 500 in ExternalToolStatus API

### ISSUE THREAD

**Issue by hackdna** [parklab/refinery-platform#427]
Sample error message from /api/v1/externaltoolstatus:
```
{
  error_message: "get() returned more than one ExternalToolStatus -- it returned 2!",
  traceback: "Traceback (most recent call last): File "/Users/isytchev/environments/refinery-platform/lib/python2.7/site-packages/tastypie/resources.py", line 202, in wrapper response = callback(request, *args, **kwargs) File "/Users/isytchev/environments/refinery-platform/lib/python2.7/site-packages/tastypie/resources.py", line 440, in dispatch_list return self.dispatch('list', request, **kwargs) File "/Users/isytchev/environments/refinery-platform/lib/python2.7/site-packages/tastypie/resources.py", line 472, in dispatch response = method(request, **kwargs) File "/Users/isytchev/environments/refinery-platform/lib/python2.7/site-packages/tastypie/resources.py", line 1285, in get_list bundles.append(self.full_dehydrate(bundle)) File "/Users/isytchev/environments/refinery-platform/lib/python2.7/site-packages/tastypie/resources.py", line 854, in full_dehydrate bundle = self.dehydrate(bundle) File "/Users/isytchev/workspace/refinery-platform/refinery/../refinery/core/api.py", line 306, in dehydrate bundle.data['status'] = check_tool_status(bundle.data['name'])[1] # call to method File "/Users/isytchev/workspace/refinery-platform/refinery/core/tasks.py", line 323, in check_tool_status tool = ExternalToolStatus.objects.get(name=tool_name) File "/Users/isytchev/environments/refinery-platform/lib/python2.7/site-packages/django/db/models/manager.py", line 143, in get return self.get_query_set().get(*args, **kwargs) File "/Users/isytchev/environments/refinery-platform/lib/python2.7/site-packages/django/db/models/query.py", line 407, in get (self.model._meta.object_name, num)) MultipleObjectsReturned: get() returned more than one ExternalToolStatus -- it returned 2! "
}
```
It appears that after editing and saving a Galaxy instance (e.g., changing API key) a new ExternalToolStatus object is created for Galaxy with the same name as the original which result in multiple objects returned by ExternalToolStatus.objects.get(name=tool_name):
```
In [10]: ExternalToolStatus.objects.all()
Out[10]: [<ExternalToolStatus: GALAXY (8a74c7353f770ebb36832536c002e6a3): SUCCESS>, <ExternalToolStatus: CELERY: SUCCESS>, <ExternalToolStatus: SOLR: SUCCESS>, <ExternalToolStatus: GALAXY (8a1c0184f8126325827aec17fa6699af): SUCCESS>]

In [11]: ExternalToolStatus.objects.get(name="GALAXY")
---------------------------------------------------------------------------
MultipleObjectsReturned                   Traceback (most recent call last)
/Users/isytchev/environments/refinery-platform/lib/python2.7/site-packages/django/core/management/commands/shell.pyc in <module>()
----> 1 ExternalToolStatus.objects.get(name="GALAXY")

/Users/isytchev/environments/refinery-platform/lib/python2.7/site-packages/django/db/models/manager.pyc in get(self, *args, **kwargs)
    141
    142     def get(self, *args, **kwargs):
--> 143         return self.get_query_set().get(*args, **kwargs)
    144
    145     def get_or_create(self, **kwargs):

/Users/isytchev/environments/refinery-platform/lib/python2.7/site-packages/django/db/models/query.pyc in get(self, *args, **kwargs)
    405         raise self.model.MultipleObjectsReturned(
    406             "get() returned more than one %s -- it returned %s!" %
--> 407             (self.model._meta.object_name, num))
    408
    409     def create(self, **kwargs):

MultipleObjectsReturned: get() returned more than one ExternalToolStatus -- it returned 2!
```

**Comment by ngehlenborg** [comment]
Closed by removal of ExternalToolStatus backend in e3d48712c4c1fcf87f3e5aa2cc7eec22245b0d04.
