### ISSUE TITLE
Problem accessing public datasets as AnonymousUser

### ISSUE THREAD

**Issue by hackdna** [parklab/refinery-platform#477]
### Configuration ###
Refinery version https://github.com/parklab/refinery-platform/releases/tag/v0.0.2
AnonymousUser is a member of Public group. Refinery is configured to authenticate against LDAP.

### Steps to reproduce ###
1. Share a dataset with the Public group using Django admin UI
2. Click on the dataset on the Home page as AnonymousUser (without logging in)

### Observed results ###
Server error displayed in the browser with the following message in the log:
```
Traceback (most recent call last):

 File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
   response = callback(request, *callback_args, **callback_kwargs)

 File "/srv/scc/apps/refinery-platform/refinery/core/views.py", line 328, in data_set
   context_instance=RequestContext(request))

 File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/django/shortcuts/__init__.py", line 29, in render_to_response
   return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)

 File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/django/template/loader.py", line 177, in render_to_string
   return t.render(context_instance)

 File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/django/template/base.py", line 140, in render
   return self._render(context)

 File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
   return self.nodelist.render(context)

 File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/django/template/base.py", line 830, in render
   bit = self.render_node(node, context)

 File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/django/template/base.py", line 844, in render_node
   return node.render(context)

 File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/django/template/loader_tags.py", line 124, in render
   return compiled_parent._render(context)

 File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
   return self.nodelist.render(context)

 File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/django/template/base.py", line 830, in render
   bit = self.render_node(node, context)

 File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/django/template/base.py", line 844, in render_node
   return node.render(context)

 File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/django/template/loader_tags.py", line 63, in render
   result = block.nodelist.render(context)

 File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/django/template/base.py", line 830, in render
   bit = self.render_node(node, context)

 File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/django/template/base.py", line 844, in render_node
   return node.render(context)

 File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/django/template/defaulttags.py", line 285, in render
   return nodelist.render(context)

 File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/django/template/base.py", line 830, in render
   bit = self.render_node(node, context)

 File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/django/template/base.py", line 844, in render_node
   return node.render(context)

 File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/django/template/defaulttags.py", line 285, in render
   return nodelist.render(context)

 File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/django/template/base.py", line 830, in render
   bit = self.render_node(node, context)

 File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/django/template/base.py", line 844, in render_node
   return node.render(context)

 File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/django/template/defaulttags.py", line 196, in render
   nodelist.append(node.render(context))

 File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/django/template/defaulttags.py", line 426, in render
   raise e

NoReverseMatch: Reverse for 'group perm.group.uuid' with arguments '()' and keyword arguments '{}' not found.
```

### Expected results ###
Dataset is displayed.

**Comment by hackdna** [comment]
Same as issue #440.
