### ISSUE TITLE
Missing project_user variable when using Fabric

### ISSUE THREAD

**Issue by hackdna** [parklab/refinery-platform#481]
```
$ fab
Traceback (most recent call last):
  File "/Users/isytchev/environments/refinery-deployment/lib/python2.7/site-packages/fabric/main.py", line 658, in main
    docstring, callables, default = load_fabfile(fabfile)
  File "/Users/isytchev/environments/refinery-deployment/lib/python2.7/site-packages/fabric/main.py", line 165, in load_fabfile
    imported = importer(os.path.splitext(fabfile)[0])
  File "/Users/isytchev/code/refinery-platform/fabfile.py", line 185, in <module>
    @with_settings(user=env.project_user)
  File "/Users/isytchev/environments/refinery-deployment/lib/python2.7/site-packages/fabric/utils.py", line 184, in __getattr__
    raise AttributeError(key)
AttributeError: project_user
```

**Comment by hackdna** [comment]
Temporary workaround in commit e5c2a18.

**Comment by hackdna** [comment]
Solved by adding project_user to .fabricrc
