### ISSUE TITLE
ISATAB file import fails due to `UnicodeDecodeError`

### ISSUE THREAD

**Issue by flekschas** [parklab/refinery-platform#563]
```
49 / 49: Successfully parsed isa_7715_612964.zip into DataSet with UUID None
```

```
2015-07-15 17:15:32 ERROR    tasks parse_isatab: *** print_exception:
[2015-07-15 17:15:32,181: WARNING/PoolWorker-32] Traceback (most recent call last):
[2015-07-15 17:15:32,181: WARNING/PoolWorker-32] File "/srv/scc/apps/refinery-platform/refinery/data_set_manager/tasks.py", line 596, in parse_isatab
[2015-07-15 17:15:32,182: WARNING/PoolWorker-32] data_uuid = create_dataset(investigation.uuid, username, public=public)
[2015-07-15 17:15:32,182: WARNING/PoolWorker-32] File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/celery/app/task/__init__.py", line 247, in __call__
[2015-07-15 17:15:32,183: WARNING/PoolWorker-32] return self.run(*args, **kwargs)
[2015-07-15 17:15:32,183: WARNING/PoolWorker-32] File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/celery/app/__init__.py", line 175, in run
[2015-07-15 17:15:32,184: WARNING/PoolWorker-32] return fun(*args, **kwargs)
[2015-07-15 17:15:32,184: WARNING/PoolWorker-32] File "/srv/scc/apps/refinery-platform/refinery/data_set_manager/tasks.py", line 405, in create_dataset
[2015-07-15 17:15:32,185: WARNING/PoolWorker-32] annotate_nodes(investigation_uuid)
[2015-07-15 17:15:32,186: WARNING/PoolWorker-32] File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/celery/app/task/__init__.py", line 247, in __call__
[2015-07-15 17:15:32,186: WARNING/PoolWorker-32] return self.run(*args, **kwargs)
[2015-07-15 17:15:32,186: WARNING/PoolWorker-32] File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/celery/app/__init__.py", line 175, in run
[2015-07-15 17:15:32,187: WARNING/PoolWorker-32] return fun(*args, **kwargs)
[2015-07-15 17:15:32,187: WARNING/PoolWorker-32] File "/srv/scc/apps/refinery-platform/refinery/data_set_manager/tasks.py", line 491, in annotate_nodes
[2015-07-15 17:15:32,188: WARNING/PoolWorker-32] index_annotated_nodes(node_type, study.uuid, assay.uuid)
[2015-07-15 17:15:32,188: WARNING/PoolWorker-32] File "/srv/scc/apps/refinery-platform/refinery/data_set_manager/utils.py", line 489, in index_annotated_nodes
[2015-07-15 17:15:32,188: WARNING/PoolWorker-32] _index_annotated_nodes(node_type, study_uuid, assay_uuid, None)
[2015-07-15 17:15:32,189: WARNING/PoolWorker-32] File "/srv/scc/apps/refinery-platform/refinery/data_set_manager/utils.py", line 518, in _index_annotated_nodes
[2015-07-15 17:15:32,189: WARNING/PoolWorker-32] node_index.update_object(node,using="data_set_manager")
[2015-07-15 17:15:32,189: WARNING/PoolWorker-32] File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/haystack/indexes.py", line 266, in update_object
[2015-07-15 17:15:32,190: WARNING/PoolWorker-32] backend.update(self, [instance])
[2015-07-15 17:15:32,190: WARNING/PoolWorker-32] File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/haystack/backends/solr_backend.py", line 66, in update
[2015-07-15 17:15:32,190: WARNING/PoolWorker-32] self.conn.add(docs, commit=commit, boost=index.get_field_weights())
[2015-07-15 17:15:32,191: WARNING/PoolWorker-32] File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/pysolr.py", line 703, in add
[2015-07-15 17:15:32,191: WARNING/PoolWorker-32] response = self._update(m, commit=commit, waitFlush=waitFlush, waitSearcher=waitSearcher)
[2015-07-15 17:15:32,191: WARNING/PoolWorker-32] File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/pysolr.py", line 401, in _update
[2015-07-15 17:15:32,192: WARNING/PoolWorker-32] return self._send_request('POST', path, message, {'Content-type': 'text/xml; charset=utf-8'})
[2015-07-15 17:15:32,192: WARNING/PoolWorker-32] File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/pysolr.py", line 332, in _send_request
[2015-07-15 17:15:32,192: WARNING/PoolWorker-32] conn.request(method, path, body, headers)
[2015-07-15 17:15:32,193: WARNING/PoolWorker-32] File "/n/sw/centos6/python-2.7.3/lib/python2.7/httplib.py", line 958, in request
[2015-07-15 17:15:32,193: WARNING/PoolWorker-32] self._send_request(method, url, body, headers)
[2015-07-15 17:15:32,194: WARNING/PoolWorker-32] File "/n/sw/centos6/python-2.7.3/lib/python2.7/httplib.py", line 992, in _send_request
[2015-07-15 17:15:32,194: WARNING/PoolWorker-32] self.endheaders(body)
[2015-07-15 17:15:32,194: WARNING/PoolWorker-32] File "/n/sw/centos6/python-2.7.3/lib/python2.7/httplib.py", line 954, in endheaders
[2015-07-15 17:15:32,195: WARNING/PoolWorker-32] self._send_output(message_body)
[2015-07-15 17:15:32,195: WARNING/PoolWorker-32] File "/n/sw/centos6/python-2.7.3/lib/python2.7/httplib.py", line 812, in _send_output
[2015-07-15 17:15:32,195: WARNING/PoolWorker-32] msg += message_body
[2015-07-15 17:15:32,196: WARNING/PoolWorker-32] UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 578: ordinal not in range(128)
2015-07-15 17:15:32 ERROR    tasks parse_isatab: None
```

**Comment by flekschas** [comment]
Must be caused by some recent changes because I already parsed that file successfully earlier.

**Comment by flekschas** [comment]
This files fails with the same error too `isa_16396_903615.zip`

**Comment by ngehlenborg** [comment]
In isa_7715_612964.zip the problem is an "EN DASH" unicode character (0xe2 0x80 0x93 or U+2013) in the value of the `Factor Value[genetic transformation]` field: "PU.1 knockdown mice with targeted disruption of the distal enhancer (URE) â€“14kb upstream of the PU.1 gene". Looks like an annotation error. It should probably say "-" (= minus).

**Comment by ngehlenborg** [comment]
In the problem is a "GREEK SMALL LETTER BETA" unicode character (0xce 0xb2 or U+03B2) in the value of the `Characteristics[treatment]` field, e.g.: "TGFÎ² (5.0 ng/ml) 1 hr".

**Comment by ngehlenborg** [comment]
It seems like in principle these unicode characters should not be causing issues. I imported `isa_7715_612964.zip` on June 19, 2015 at 12:35 p.m. The "EN DASH" is showing up correctly in the file browser.
