### ISSUE TITLE
ISATAB parser fails to create a data set.

### ISSUE THREAD

**Issue by flekschas** [parklab/refinery-platform#570]
Trying to import `isa_16347_631295.zip` leads to

```
Successfully parsed isa_16347_631295.zip into DataSet with UUID None
```

`celeryd-w1.log` says:

```
[2015-07-16 19:00:05,904: WARNING/PoolWorker-2] Traceback (most recent call last):
[2015-07-16 19:00:05,904: WARNING/PoolWorker-2] File "/vagrant/refinery/data_set_manager/tasks.py", line 608, in parse_isatab
[2015-07-16 19:00:05,905: WARNING/PoolWorker-2] data_uuid = create_dataset(investigation.uuid, username, public=public)
[2015-07-16 19:00:05,905: WARNING/PoolWorker-2] File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/celery/app/task/__init__.py", line 247, in __call__
[2015-07-16 19:00:05,906: WARNING/PoolWorker-2] return self.run(*args, **kwargs)
[2015-07-16 19:00:05,906: WARNING/PoolWorker-2] File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/celery/app/__init__.py", line 175, in run
[2015-07-16 19:00:05,906: WARNING/PoolWorker-2] return fun(*args, **kwargs)
[2015-07-16 19:00:05,907: WARNING/PoolWorker-2] File "/vagrant/refinery/data_set_manager/tasks.py", line 405, in create_dataset
[2015-07-16 19:00:05,908: WARNING/PoolWorker-2] annotate_nodes(investigation_uuid)
[2015-07-16 19:00:05,908: WARNING/PoolWorker-2] File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/celery/app/task/__init__.py", line 247, in __call__
[2015-07-16 19:00:05,908: WARNING/PoolWorker-2] return self.run(*args, **kwargs)
[2015-07-16 19:00:05,909: WARNING/PoolWorker-2] File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/celery/app/__init__.py", line 175, in run
[2015-07-16 19:00:05,909: WARNING/PoolWorker-2] return fun(*args, **kwargs)
[2015-07-16 19:00:05,909: WARNING/PoolWorker-2] File "/vagrant/refinery/data_set_manager/tasks.py", line 494, in annotate_nodes
[2015-07-16 19:00:05,910: WARNING/PoolWorker-2] attribute_count = initialize_attribute_order(study, assay)
[2015-07-16 19:00:05,910: WARNING/PoolWorker-2] File "/vagrant/refinery/data_set_manager/models.py", line 719, in initialize_attribute_order
[2015-07-16 19:00:05,911: WARNING/PoolWorker-2] for key in results["response"]["docs"][0]:
[2015-07-16 19:00:05,911: WARNING/PoolWorker-2] IndexError: list index out of range
```

**Comment by flekschas** [comment]
The problem is that `initialize_attribute_order()` assumes that [Solr always returns results](https://github.com/parklab/refinery-platform/blob/develop/refinery/data_set_manager/models.py#L719), which is obviously not the case.

Here is what Solr returns:
```
{
    "responseHeader": {
        "status": 0,
        "QTime": 7,
        "params": {
            "facet": "true",
            "facet.sort": "count",
            "start": "0",
            "q": "django_ct:data_set_manager.node",
            "facet.limit": "-1",
            "wt": "json",
            "fq": "(study_uuid:1d4628a2-83a0-42d8-b930-f75906b62e22 AND assay_uuid:626d01ad-5d53-49e4-9134-bd391da7927f AND is_annotation:false AND (type:\"Array Data File\" OR type:\"Derived Array Data File\" OR type:\"Raw Data File\" OR type: \"Derived Data File\"))",
            "rows": "1"
        }
    },
    "response": {
        "numFound": 0,
        "start": 0,
        "docs": []
    },
    "facet_counts": {
        "facet_queries": {},
        "facet_fields": {},
        "facet_dates": {},
        "facet_ranges": {}
    }
}
```

**Comment by flekschas** [comment]
The reason why Solr doesn't find anything is because there are no `node_types`.

**Comment by flekschas** [comment]
Fixing the initial error allows importing but causes trouble when browsing the data set. (Did I open Pandora's box?)
![bildschirmfoto 2015-07-16 um 19 40 36](https://cloud.githubusercontent.com/assets/932103/8737664/be12a4d0-2bf2-11e5-9b11-c62699dfab13.PNG)

**Comment by ngehlenborg** [comment]
Turns out there are no data files listed in this data set (the "raw data file" column is empty). Broken ISA-Tab.
