### ISSUE TITLE
analysis and visualization controls not showing in production mode

### ISSUE THREAD

**Issue by ngehlenborg** [parklab/refinery-platform#638]
__Reproduce__
Run developer VM in production mode using `fab vm conf:prod` and view a data set with change permissions. Click "Analyze" or "Visualize" button.

__Observed__
![screen shot 2015-08-26 at 9 52 03 am](https://cloud.githubusercontent.com/assets/1216518/9495166/2518990a-4bd8-11e5-9c2b-65807ba114c4.png)

The console error is:
```js
Error: [$injector:unpr] Unknown provider: bProvider <- b
http://errors.angularjs.org/1.4.4/$injector/unpr?p0=bProvider%20%3C-%20b
    at REGEX_STRING_REGEXP (http://192.168.50.50/static/vendor/angular/angular.js:68:12)
    at http://192.168.50.50/static/vendor/angular/angular.js:4284:19
    at Object.getService [as get] (http://192.168.50.50/static/vendor/angular/angular.js:4432:39)
    at http://192.168.50.50/static/vendor/angular/angular.js:4289:45
    at getService (http://192.168.50.50/static/vendor/angular/angular.js:4432:39)
    at invoke (http://192.168.50.50/static/vendor/angular/angular.js:4464:13)
    at Object.instantiate (http://192.168.50.50/static/vendor/angular/angular.js:4481:27)
    at http://192.168.50.50/static/vendor/angular/angular.js:9108:28
    at compile (http://192.168.50.50/static/vendor/angular-ui-router/release/angular-ui-router.min.js:7:23333)
    at invokeLinkFn (http://192.168.50.50/static/vendor/angular/angular.js:8746:9) <div ui-view="" class="ng-enter" data-ng-animate="1" style="transition-delay: -9999s;">
```

__Expected__
No gap to the left of the file browser and analysis or visualization controls showing when "Analyze" or "Visualize" are selected, respectively.

**Comment by ngehlenborg** [comment]
The problem also occurs when using the `fab vm conf:dev` config.
