### ISSUE TITLE
"vagrant up" fails in `gem install librarian-puppet -v 2.1.0` step

### ISSUE THREAD

**Issue by drj11** [parklab/refinery-platform#665]
When I follow the instructions in the README.md I get the following huge error message at the `vagrant up` phase:

```
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'ubuntu/trusty64'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: Setting the name of the VM: refinery-platform_default_1441200398722_38768
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 => 2222 (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
    default: 
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default: 
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Setting hostname...
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...
    default: /vagrant => /home/drj/sitran/refinery-platform
    default: /tmp/vagrant-puppet/modules-cd7a13c1032a565791820c7e4025a8b1 => /home/drj/sitran/refinery-platform/deployment/modules
    default: /tmp/vagrant-puppet/manifests-bd893fa5c367709cab8bdf7be781f155 => /home/drj/sitran/refinery-platform/deployment/manifests
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: stdin: is not a tty
==> default: Reading package lists...
==> default: Building dependency tree...
==> default: Reading state information...
==> default: The following extra packages will be installed:
==> default:   git-man liberror-perl ruby1.9.1-dev
==> default: Suggested packages:
==> default:   git-daemon-run git-daemon-sysvinit git-doc git-el git-email git-gui gitk
==> default:   gitweb git-arch git-bzr git-cvs git-mediawiki git-svn
==> default: The following NEW packages will be installed:
==> default:   git git-man liberror-perl ruby-dev ruby1.9.1-dev
==> default: 0 upgraded, 5 newly installed, 0 to remove and 0 not upgraded.
==> default: Need to get 4,222 kB of archives.
==> default: After this operation, 25.8 MB of additional disk space will be used.
==> default: Get:1 http://archive.ubuntu.com/ubuntu/ trusty/main liberror-perl all 0.17-1.1 [21.1 kB]
==> default: Get:2 http://archive.ubuntu.com/ubuntu/ trusty-updates/main git-man all 1:1.9.1-1ubuntu0.1 [698 kB]
==> default: Get:3 http://archive.ubuntu.com/ubuntu/ trusty-updates/main git amd64 1:1.9.1-1ubuntu0.1 [2,627 kB]
==> default: Get:4 http://archive.ubuntu.com/ubuntu/ trusty-updates/main ruby1.9.1-dev amd64 1.9.3.484-2ubuntu1.2 [871 kB]
==> default: Get:5 http://archive.ubuntu.com/ubuntu/ trusty/main ruby-dev all 1:1.9.3.4 [4,660 B]
==> default: Fetched 4,222 kB in 1s (2,292 kB/s)
==> default: Selecting previously unselected package liberror-perl.
==> default: (Reading database ... 61001 files and directories currently installed.)
==> default: Preparing to unpack .../liberror-perl_0.17-1.1_all.deb ...
==> default: Unpacking liberror-perl (0.17-1.1) ...
==> default: Selecting previously unselected package git-man.
==> default: Preparing to unpack .../git-man_1%3a1.9.1-1ubuntu0.1_all.deb ...
==> default: Unpacking git-man (1:1.9.1-1ubuntu0.1) ...
==> default: Selecting previously unselected package git.
==> default: Preparing to unpack .../git_1%3a1.9.1-1ubuntu0.1_amd64.deb ...
==> default: Unpacking git (1:1.9.1-1ubuntu0.1) ...
==> default: Selecting previously unselected package ruby1.9.1-dev.
==> default: Preparing to unpack .../ruby1.9.1-dev_1.9.3.484-2ubuntu1.2_amd64.deb ...
==> default: Unpacking ruby1.9.1-dev (1.9.3.484-2ubuntu1.2) ...
==> default: Selecting previously unselected package ruby-dev.
==> default: Preparing to unpack .../ruby-dev_1%3a1.9.3.4_all.deb ...
==> default: Unpacking ruby-dev (1:1.9.3.4) ...
==> default: Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
==> default: Setting up liberror-perl (0.17-1.1) ...
==> default: Setting up git-man (1:1.9.1-1ubuntu0.1) ...
==> default: Setting up git (1:1.9.1-1ubuntu0.1) ...
==> default: Setting up ruby1.9.1-dev (1.9.3.484-2ubuntu1.2) ...
==> default: Setting up ruby-dev (1:1.9.3.4) ...
==> default: Successfully installed thor-0.19.1
==> default: Successfully installed librarianp-0.6.3
==> default: Successfully installed rsync-1.0.9
==> default: Successfully installed multipart-post-2.0.0
==> default: Successfully installed faraday-0.9.1
==> default: Successfully installed faraday_middleware-0.9.2
==> default: Successfully installed semantic_puppet-0.1.1
==> default: Successfully installed minitar-0.5.4
==> default: Successfully installed puppet_forge-2.1.0
==> default: Successfully installed librarian-puppet-2.1.0
==> default: 10 gems installed
==> default: Installing ri documentation for thor-0.19.1...
==> default: Installing ri documentation for librarianp-0.6.3...
==> default: Installing ri documentation for rsync-1.0.9...
==> default: Installing ri documentation for multipart-post-2.0.0...
==> default: Installing ri documentation for faraday-0.9.1...
==> default: Installing ri documentation for faraday_middleware-0.9.2...
==> default: Installing ri documentation for semantic_puppet-0.1.1...
==> default: Installing ri documentation for minitar-0.5.4...
==> default: Installing ri documentation for puppet_forge-2.1.0...
==> default: Installing ri documentation for librarian-puppet-2.1.0...
==> default: Installing RDoc documentation for thor-0.19.1...
==> default: Installing RDoc documentation for librarianp-0.6.3...
==> default: Installing RDoc documentation for rsync-1.0.9...
==> default: Installing RDoc documentation for multipart-post-2.0.0...
==> default: Installing RDoc documentation for faraday-0.9.1...
==> default: Installing RDoc documentation for faraday_middleware-0.9.2...
==> default: Installing RDoc documentation for semantic_puppet-0.1.1...
==> default: Installing RDoc documentation for minitar-0.5.4...
==> default: Installing RDoc documentation for puppet_forge-2.1.0...
==> default: Installing RDoc documentation for librarian-puppet-2.1.0...
==> default: /var/lib/gems/1.9.1/gems/librarian-puppet-2.1.0/lib/librarian/puppet/util.rb:51:in `normalize_name'
==> default: : 
==> default: undefined method `sub' for nil:NilClass
==> default:  (
==> default: NoMethodError
==> default: )
==> default: 	from /var/lib/gems/1.9.1/gems/librarian-puppet-2.1.0/lib/librarian/puppet/dependency.rb:12:in `initialize'
==> default: 	from /var/lib/gems/1.9.1/gems/librarian-puppet-2.1.0/lib/librarian/puppet/source/forge.rb:147:in `new'
==> default: 	from /var/lib/gems/1.9.1/gems/librarian-puppet-2.1.0/lib/librarian/puppet/source/forge.rb:147:in `block in fetch_dependencies'
==> default: 	from /var/lib/gems/1.9.1/gems/librarian-puppet-2.1.0/lib/librarian/puppet/source/forge.rb:145:in `each'
==> default: 	from /var/lib/gems/1.9.1/gems/librarian-puppet-2.1.0/lib/librarian/puppet/source/forge.rb:145:in `map'
==> default: 	from /var/lib/gems/1.9.1/gems/librarian-puppet-2.1.0/lib/librarian/puppet/source/forge.rb:145:in `fetch_dependencies'
==> default: 	from /var/lib/gems/1.9.1/gems/librarianp-0.6.3/lib/librarian/manifest.rb:97:in `fetch_dependencies!'
==> default: 	from /var/lib/gems/1.9.1/gems/librarianp-0.6.3/lib/librarian/manifest.rb:89:in `fetched_dependencies'
==> default: 	from /var/lib/gems/1.9.1/gems/librarianp-0.6.3/lib/librarian/manifest.rb:46:in `dependencies'
==> default: 	from /var/lib/gems/1.9.1/gems/librarianp-0.6.3/lib/librarian/manifest.rb:63:in `exclude_dependencies!'
==> default: 	from /var/lib/gems/1.9.1/gems/librarianp-0.6.3/lib/librarian/resolver/implementation.rb:67:in `block in do_resolve'
==> default: 	from /var/lib/gems/1.9.1/gems/librarianp-0.6.3/lib/librarian/resolver/implementation.rb:161:in `block (3 levels) in resolving_dependency_map_find_manifests'
==> default: 	from /var/lib/gems/1.9.1/gems/librarianp-0.6.3/lib/librarian/resolver/implementation.rb:194:in `block in scope_checking_manifest'
==> default: 	from /var/lib/gems/1.9.1/gems/librarianp-0.6.3/lib/librarian/resolver/implementation.rb:230:in `scope'
==> default: 	from /var/lib/gems/1.9.1/gems/librarianp-0.6.3/lib/librarian/resolver/implementation.rb:193:in `scope_checking_manifest'
==> default: 	from /var/lib/gems/1.9.1/gems/librarianp-0.6.3/lib/librarian/resolver/implementation.rb:160:in `block (2 levels) in resolving_dependency_map_find_manifests'
==> default: 	from /var/lib/gems/1.9.1/gems/librarianp-0.6.3/lib/librarian/resolver/implementation.rb:218:in `block in map_find'
==> default: 	from /var/lib/gems/1.9.1/gems/librarianp-0.6.3/lib/librarian/resolver/implementation.rb:217:in `each'
==> default: 	from /var/lib/gems/1.9.1/gems/librarianp-0.6.3/lib/librarian/resolver/implementation.rb:217:in `map_find'
==> default: 	from /var/lib/gems/1.9.1/gems/librarianp-0.6.3/lib/librarian/resolver/implementation.rb:159:in `block in resolving_dependency_map_find_manifests'
==> default: 	from /var/lib/gems/1.9.1/gems/librarianp-0.6.3/lib/librarian/resolver/implementation.rb:172:in `block (2 levels) in scope_resolving_dependency'
==> default: 	from /var/lib/gems/1.9.1/gems/librarianp-0.6.3/lib/librarian/resolver/implementation.rb:186:in `block in scope_checking_manifests'
==> default: 	from /var/lib/gems/1.9.1/gems/librarianp-0.6.3/lib/librarian/resolver/implementation.rb:230:in `scope'
==> default: 	from /var/lib/gems/1.9.1/gems/librarianp-0.6.3/lib/librarian/resolver/implementation.rb:185:in `scope_checking_manifests'
==> default: 	from /var/lib/gems/1.9.1/gems/librarianp-0.6.3/lib/librarian/resolver/implementation.rb:171:in `block in scope_resolving_dependency'
==> default: 	from /var/lib/gems/1.9.1/gems/librarianp-0.6.3/lib/librarian/resolver/implementation.rb:230:in `scope'
==> default: 	from /var/lib/gems/1.9.1/gems/librarianp-0.6.3/lib/librarian/resolver/implementation.rb:170:in `scope_resolving_dependency'
==> default: 	from /var/lib/gems/1.9.1/gems/librarianp-0.6.3/lib/librarian/resolver/implementation.rb:158:in `resolving_dependency_map_find_manifests'
==> default: 	from /var/lib/gems/1.9.1/gems/librarianp-0.6.3/lib/librarian/resolver/implementation.rb:65:in `do_resolve'
==> default: 	from /var/lib/gems/1.9.1/gems/librarianp-0.6.3/lib/librarian/resolver/implementation.rb:50:in `resolve'
==> default: 	from /var/lib/gems/1.9.1/gems/librarianp-0.6.3/lib/librarian/resolver.rb:23:in `resolve'
==> default: 	from /var/lib/gems/1.9.1/gems/librarianp-0.6.3/lib/librarian/action/resolve.rb:31:in `run'
==> default: 	from /var/lib/gems/1.9.1/gems/librarian-puppet-2.1.0/lib/librarian/puppet/action/resolve.rb:8:in `run'
==> default: 	from /var/lib/gems/1.9.1/gems/librarian-puppet-2.1.0/lib/librarian/puppet/cli.rb:104:in `resolve!'
==> default: 	from /var/lib/gems/1.9.1/gems/librarian-puppet-2.1.0/lib/librarian/puppet/cli.rb:68:in `install'
==> default: 	from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
==> default: 	from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
==> default: 	from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
==> default: 	from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
==> default: 	from /var/lib/gems/1.9.1/gems/librarianp-0.6.3/lib/librarian/cli.rb:26:in `block (2 levels) in bin!'
==> default: 	from /var/lib/gems/1.9.1/gems/librarianp-0.6.3/lib/librarian/cli.rb:31:in `returning_status'
==> default: 	from /var/lib/gems/1.9.1/gems/librarianp-0.6.3/lib/librarian/cli.rb:26:in `block in bin!'
==> default: 	from /var/lib/gems/1.9.1/gems/librarianp-0.6.3/lib/librarian/cli.rb:47:in `with_environment'
==> default: 	from /var/lib/gems/1.9.1/gems/librarianp-0.6.3/lib/librarian/cli.rb:26:in `bin!'
==> default: 	from /var/lib/gems/1.9.1/gems/librarian-puppet-2.1.0/bin/librarian-puppet:7:in `<top (required)>'
==> default: 	from /usr/local/bin/librarian-puppet:23:in `load'
==> default: 	from /usr/local/bin/librarian-puppet:23:in `<main>'
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**Comment by drj11** [comment]
Trying `vagrant provision` doesn't fix things. Same error message.

**Comment by drj11** [comment]
Just for the record, I'm on Ubuntu 14.04 LTS, vagrant 1.7.4, VirtualBox 4.3.30

**Comment by hackdna** [comment]
I can reproduce it with Vagrant 1.7.2 and VirtualBox 4.3.26.

**Comment by drj11** [comment]
I just tried `vagrant ssh` then `sudo gem install librarian-puppet -v 2.1.0` and that worked:

```
vagrant@refinery:~$ sudo gem install librarian-puppet -v 2.1.0
Successfully installed librarian-puppet-2.1.0
1 gem installed
Installing ri documentation for librarian-puppet-2.1.0...
Installing RDoc documentation for librarian-puppet-2.1.0...
```

**Comment by drj11** [comment]
By using `vagrant ssh` and trying by hand, I discovered that it's the `librarian-puppet install` step:

```
$ sudo librarian-puppet install
/var/lib/gems/1.9.1/gems/librarian-puppet-2.1.0/lib/librarian/puppet/util.rb:51:in `normalize_name': undefined method `sub' for nil:NilClass (NoMethodError)
	from /var/lib/gems/1.9.1/gems/librarian-puppet-2.1.0/lib/librarian/puppet/dependency.rb:12:in `initialize'
```
