### ISSUE TITLE
Empty dataset page for "15826: ChipSeq of MLL1 in mouse leukemic blast cells" at refinery-dev

### ISSUE THREAD

**Issue by flekschas** [parklab/refinery-platform#670]
Reproduce:
https://refinery-dev.stemcellcommons.org/data_sets/fe9edc18-ae83-4956-b6a5-76cd3ba4f704/#/files/browse

Expected:
Dataset page

Seen:
Empty dataset page

The console reports a 500 error when trying to get the following resource.

```
https://refinery-dev.stemcellcommons.org/solr/data_set_manager/select/?q=django_ct:data_set_manager.node&wt=json&json.wrf=jQuery211006564751104451716_1441733896774&start=0&rows=20&fq=(study_uuid:393f8727-ae24-4744-abc9-20fd99d5124f%20AND%20assay_uuid:6b22580a-d1c0-4309-bc7d-ea52eb28cf68)&fq=type:(%22Raw%20Data%20File%22%20OR%20%22Derived%20Data%20File%22%20OR%20%22Array%20Data%20File%22%20OR%20%22Derived%20Array%20Data%20File%22%20OR%20%22Array%20Data%20Matrix%20File%22%20OR%20%22Derived%20Array%20Data%20Matrix%20File%22)&fq=is_annotation:false&facet.field=REFINERY_ANALYSIS_UUID_1556_787_s&facet.field=REFINERY_WORKFLOW_OUTPUT_1556_787_s&facet.field=REFINERY_SUBANALYSIS_1556_787_s&facet.sort=count&facet.limit=-1&facet=true&fl=Replicate_Id_Comment_1556_787_s,file_uuid,name,REFINERY_TYPE_1556_787_s,organism_Characteristics_1556_787_s,REFINERY_ANALYSIS_UUID_1556_787_s,notes_Characteristics_1556_787_s,type,study_uuid,cell_type_Characteristics_1556_787_s,genotype_Characteristics_1556_787_s,Group_Name_Comment_1556_787_s,REFINERY_FILETYPE_1556_787_s,REFINERY_NAME_1556_787_s,uuid,strain_Characteristics_1556_787_s,assay_uuid,REFINERY_WORKFLOW_OUTPUT_1556_787_s,is_annotation,REFINERY_SUBANALYSIS_1556_787_s&sort=Replicate_Id_Comment_1556_787_s%20asc&facet.pivot=,&_=1441733896778
```

**Comment by ngehlenborg** [comment]
This probably because Solr is down. But I agree that there should an error message.

**Comment by flekschas** [comment]
Other dataset pages just worked fine and I was able to search so Solr must have been running.

**Comment by hackdna** [comment]
From the log:

```
Traceback (most recent call last):

  File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)

  File "/srv/scc/apps/refinery-platform/refinery/core/views.py", line 606, in solr_select
    f = urllib2.urlopen(req)

  File "/n/sw/centos6/python-2.7.3/lib/python2.7/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)

  File "/n/sw/centos6/python-2.7.3/lib/python2.7/urllib2.py", line 406, in open
    response = meth(req, response)

  File "/n/sw/centos6/python-2.7.3/lib/python2.7/urllib2.py", line 519, in http_response
    'http', request, response, code, msg, hdrs)

  File "/n/sw/centos6/python-2.7.3/lib/python2.7/urllib2.py", line 444, in error
    return self._call_chain(*args)

  File "/n/sw/centos6/python-2.7.3/lib/python2.7/urllib2.py", line 378, in _call_chain
    result = func(*args)

  File "/n/sw/centos6/python-2.7.3/lib/python2.7/urllib2.py", line 527, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

HTTPError: HTTP Error 400: Bad Request


<WSGIRequest
path:/solr/data_set_manager/select/,
GET:<QueryDict: {u'sort': [u'Replicate_Id_Comment_1556_787_s asc'], u'fq': [u'(study_uuid:393f8727-ae24-4744-abc9-20fd99d5124f AND assay_uuid:6b22580a-d1c0-4309-bc7d-ea52eb28cf68)', u'type:("Raw Data File" OR "Derived Data File" OR "Array Data File" OR "Derived Array Data File" OR "Array Data Matrix File" OR "Derived Array Data Matrix File")', u'is_annotation:false'], u'rows': [u'20'], u'facet.field': [u'REFINERY_ANALYSIS_UUID_1556_787_s', u'REFINERY_WORKFLOW_OUTPUT_1556_787_s', u'REFINERY_SUBANALYSIS_1556_787_s'], u'facet.limit': [u'-1'], u'facet.sort': [u'count'], u'facet': [u'true'], u'json.wrf': [u'jQuery21107747754578012973_1441736033547'], u'q': [u'django_ct:data_set_manager.node'], u'start': [u'0'], u'wt': [u'json'], u'facet.pivot': [u','], u'fl': [u'Replicate_Id_Comment_1556_787_s,file_uuid,name,REFINERY_TYPE_1556_787_s,organism_Characteristics_1556_787_s,REFINERY_ANALYSIS_UUID_1556_787_s,notes_Characteristics_1556_787_s,type,study_uuid,cell_type_Characteristics_1556_
787_s,genotype_Characteristics_1556_787_s,Group_Name_Comment_1556_787_s,REFINERY_FILETYPE_1556_787_s,REFINERY_NAME_1556_787_s,uuid,strain_Characteristics_1556_787_s,assay_uuid,REFINERY_WORKFLOW_OUTPUT_1556_787_s,is_annotation,REFINERY_SUBANALYSIS_1556_787_s'], u'_': [u'1441736033551']}>,
POST:<QueryDict: {}>,
COOKIES:{'csrftoken': 'CrNwgBU22KU5tVJvoVPD1VlAN55MVku7',
'sessionid': '9hrk6op9entbrvkl9im6f31uj4ilp6fg'},
META:{u'CSRF_COOKIE': u'CrNwgBU22KU5tVJvoVPD1VlAN55MVku7',
'DJANGO_SETTINGS_MODULE': 'config.settings.prod',
'DOCUMENT_ROOT': '/var/www/html',
'GATEWAY_INTERFACE': 'CGI/1.1',
'HTTP_ACCEPT': 'text/javascript, application/javascript, application/ecmascript, application/x-ecmascript, */*; q=0.01',
'HTTP_ACCEPT_ENCODING': 'gzip, deflate, sdch',
'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.8',
'HTTP_CONNECTION': 'keep-alive',
'HTTP_COOKIE': 'sessionid=9hrk6op9entbrvkl9im6f31uj4ilp6fg; csrftoken=CrNwgBU22KU5tVJvoVPD1VlAN55MVku7',
'HTTP_DNT': '1',
'HTTP_HOST': 'refinery-dev.stemcellcommons.org',
'HTTP_REFERER': 'https://refinery-dev.stemcellcommons.org/data_sets/fe9edc18-ae83-4956-b6a5-76cd3ba4f704/',
'HTTP_USER_AGENT': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36',
'HTTP_X_REQUESTED_WITH': 'XMLHttpRequest',
'PATH_INFO': u'/solr/data_set_manager/select/',
'PATH_TRANSLATED': '/srv/scc/apps/refinery-platform/refinery/config/wsgi.py/solr/data_set_manager/select/',
'QUERY_STRING': 'q=django_ct:data_set_manager.node&wt=json&json.wrf=jQuery21107747754578012973_1441736033547&start=0&rows=20&fq=(study_uuid:393f8727-ae24-4744-abc9-20fd99d5124f%20AND%20assay_uuid:6b22580a-d1c0-4309-bc7d-ea52eb28cf68)&fq=type:(%22Raw%20Data%20File%22%20OR%20%22Derived%20Data%20File%22%20OR%20%22Array%20Data%20File%22%20OR%20%22Derived%20Array%20Data%20File%22%20OR%20%22Array%20Data%20Matrix%20File%22%20OR%20%22Derived%20Array%20Data%20Matrix%20File%22)&fq=is_annotation:false&facet.field=REFINERY_ANALYSIS_UUID_1556_787_s&facet.field=REFINERY_WORKFLOW_OUTPUT_1556_787_s&facet.field=REFINERY_SUBANALYSIS_1556_787_s&facet.sort=count&facet.limit=-1&facet=true&fl=Replicate_Id_Comment_1556_787_s,file_uuid,name,REFINERY_TYPE_1556_787_s,organism_Characteristics_1556_787_s,REFINERY_ANALYSIS_UUID_1556_787_s,notes_Characteristics_1556_787_s,type,study_uuid,cell_type_Characteristics_1556_787_s,genotype_Characteristics_1556_787_s,Group_Name_Comment_1556_787_s,REFINERY_FILETY
PE_1556_787_s,REFINERY_NAME_1556_787_s,uuid,strain_Characteristics_1556_787_s,assay_uuid,REFINERY_WORKFLOW_OUTPUT_1556_787_s,is_annotation,REFINERY_SUBANALYSIS_1556_787_s&sort=Replicate_Id_Comment_1556_787_s%20asc&facet.pivot=,&_=1441736033551',
'REMOTE_ADDR': '134.174.140.208',
'REMOTE_PORT': '44637',
'REQUEST_METHOD': 'GET',
'REQUEST_URI': '/solr/data_set_manager/select/?q=django_ct:data_set_manager.node&wt=json&json.wrf=jQuery21107747754578012973_1441736033547&start=0&rows=20&fq=(study_uuid:393f8727-ae24-4744-abc9-20fd99d5124f%20AND%20assay_uuid:6b22580a-d1c0-4309-bc7d-ea52eb28cf68)&fq=type:(%22Raw%20Data%20File%22%20OR%20%22Derived%20Data%20File%22%20OR%20%22Array%20Data%20File%22%20OR%20%22Derived%20Array%20Data%20File%22%20OR%20%22Array%20Data%20Matrix%20File%22%20OR%20%22Derived%20Array%20Data%20Matrix%20File%22)&fq=is_annotation:false&facet.field=REFINERY_ANALYSIS_UUID_1556_787_s&facet.field=REFINERY_WORKFLOW_OUTPUT_1556_787_s&facet.field=REFINERY_SUBANALYSIS_1556_787_s&facet.sort=count&facet.limit=-1&facet=true&fl=Replicate_Id_Comment_1556_787_s,file_uuid,name,REFINERY_TYPE_1556_787_s,organism_Characteristics_1556_787_s,REFINERY_ANALYSIS_UUID_1556_787_s,notes_Characteristics_1556_787_s,type,study_uuid,cell_type_Characteristics_1556_787_s,genotype_Characteristics_1556_787_s,Group_Name_Comm
ent_1556_787_s,REFINERY_FILETYPE_1556_787_s,REFINERY_NAME_1556_787_s,uuid,strain_Characteristics_1556_787_s,assay_uuid,REFINERY_WORKFLOW_OUTPUT_1556_787_s,is_annotation,REFINERY_SUBANALYSIS_1556_787_s&sort=Replicate_Id_Comment_1556_787_s%20asc&facet.pivot=,&_=1441736033551',
'SCRIPT_FILENAME': '/srv/scc/apps/refinery-platform/refinery/config/wsgi.py',
'SCRIPT_NAME': u'',
'SERVER_ADDR': '10.242.110.105',
'SERVER_ADMIN': 'root@localhost',
'SERVER_NAME': 'refinery-dev.stemcellcommons.org',
'SERVER_PORT': '443',
'SERVER_PROTOCOL': 'HTTP/1.1',
'SERVER_SIGNATURE': '<address>Apache/2.2.15 (CentOS) Server at refinery-dev.stemcellcommons.org Port 443</address>\n',
'SERVER_SOFTWARE': 'Apache/2.2.15 (CentOS)',
'SSL_TLS_SNI': 'refinery-dev.stemcellcommons.org',
'apache.version': (2, 2, 15),
'mod_wsgi.application_group': 'refinery-dev.stemcellcommons.org|',
'mod_wsgi.callable_object': 'application',
'mod_wsgi.daemon_connects': '1',
'mod_wsgi.daemon_restarts': '0',
'mod_wsgi.daemon_start': '1441736034642690',
'mod_wsgi.enable_sendfile': '0',
'mod_wsgi.handler_script': '',
'mod_wsgi.input_chunked': '0',
'mod_wsgi.listener_host': '',
'mod_wsgi.listener_port': '443',
'mod_wsgi.process_group': 'scc',
'mod_wsgi.queue_start': '1441736034642512',
'mod_wsgi.request_handler': 'wsgi-script',
'mod_wsgi.request_start': '1441736034642219',
'mod_wsgi.script_reloading': '1',
'mod_wsgi.script_start': '1441736034646735',
'mod_wsgi.version': (4, 3, 1),
'wsgi.errors': <mod_wsgi.Log object at 0x7f21031a5150>,
'wsgi.file_wrapper': <type 'mod_wsgi.FileWrapper'>,
'wsgi.input': <mod_wsgi.Input object at 0x7f21022db9b0>,
'wsgi.multiprocess': False,
'wsgi.multithread': True,
'wsgi.run_once': False,
'wsgi.url_scheme': 'https',
'wsgi.version': (1, 0)}>
```

**Comment by scottx611x** [comment]
Solr is definitely running while this issue occurs. Does anyone have some insight as to where the real problem is stemming from here?

**Comment by scottx611x** [comment]
Error from solr.log
```
2015-09-22 15:14:32,520 [qtp52581774-19] ERROR [org.apache.solr.core.SolrCore] - org.apache.solr.common.SolrException: Pivot Facet needs at least two fields: ,
        at org.apache.solr.handler.component.PivotFacetHelper.process(PivotFacetHelper.java:76)
        at org.apache.solr.handler.component.FacetComponent.process(FacetComponent.java:85)
        at org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:208)
        at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:135)
        at org.apache.solr.core.SolrCore.execute(SolrCore.java:1904)
        at org.apache.solr.servlet.SolrDispatchFilter.execute(SolrDispatchFilter.java:659)
        at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:362)
        at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:158)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1419)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:455)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1075)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:384)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1009)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
        at org.eclipse.jetty.server.Server.handle(Server.java:368)
        at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
        at org.eclipse.jetty.server.BlockingHttpConnection.handleRequest(BlockingHttpConnection.java:53)
        at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:953)
        at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1014)
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:861)
        at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
        at org.eclipse.jetty.server.BlockingHttpConnection.handle(BlockingHttpConnection.java:72)
        at org.eclipse.jetty.server.bio.SocketConnector$ConnectorEndPoint.run(SocketConnector.java:264)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by ngehlenborg** [comment]
It seems that this issue arises because this specific data set has only a single sample/file. All facets get deactivated upon import (because there is no point in having facets with a single facet value that is associated with a single file). We need to address this in the UI code to deal with situations in which there is no facet. We might actually want to leave all facets turned on at import time and then just hide them via the UI (offers more flexibility).

**Comment by ngehlenborg** [comment]
Related to #729?

**Comment by jkmarx** [comment]
@flekschas Could you reproduce this error locally before?

**Comment by flekschas** [comment]
@jkmarx yes

**Comment by jkmarx** [comment]
@flekschas Can you try it again sometime with the latest code? I think it was fixed when I addressed #729.

**Comment by flekschas** [comment]
@jkmarx Still seeing an error after pulling the latest code

**Comment by flekschas** [comment]
The 500 error is triggered by this method call: https://github.com/parklab/refinery-platform/blob/develop/refinery/static/source/js/refinery/solr/solr_client.js#L110

Which is in turn triggered by https://github.com/parklab/refinery-platform/blob/develop/refinery/static/source/js/refinery/contents.js#L388

**Comment by scottx611x** [comment]
I am able to reproduce this error, but I am also seeing the single file displayed to me.

See:
![screen shot 2015-10-19 at 2 12 22 pm](https://cloud.githubusercontent.com/assets/5629547/10586701/74f7b93e-766b-11e5-9978-a1947c9c8ef7.png)
