### ISSUE TITLE
Dataset Manager API does not have failsafe when solr is down

### ISSUE THREAD

**Issue by jkmarx** [parklab/refinery-platform#680]
### Reproduce
1) supervisorctl stop solr
2) Either search for a dataset in the dashboard or go to a dataset view.

### Observed
1) The dashboard will keep flashing the loading sign or the dataset view will not load.
2) The console will flash the following screen.
<img width="720" alt="screen shot 2015-09-11 at 9 03 44 am" src="https://cloud.githubusercontent.com/assets/9956764/9815753/6d0e5340-5866-11e5-8dca-c2218f30a863.png">
<img width="1428" alt="screen shot 2015-09-11 at 9 06 56 am" src="https://cloud.githubusercontent.com/assets/9956764/9815758/7310d420-5866-11e5-96ac-1a12418ca93e.png">

### Expected 
1) The dashboard & dataset view should have an error message or notice when solr is down.

**Comment by hackdna** [comment]
In addition, the following error is logged on the server side:
```
Traceback (most recent call last):

  File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)

  File "/srv/scc/apps/refinery-platform/refinery/core/views.py", line 557, in solr_select
    f = urllib2.urlopen(req)

  File "/n/sw/centos6/python-2.7.3/lib/python2.7/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)

  File "/n/sw/centos6/python-2.7.3/lib/python2.7/urllib2.py", line 400, in open
    response = self._open(req, data)

  File "/n/sw/centos6/python-2.7.3/lib/python2.7/urllib2.py", line 418, in _open
    '_open', req)

  File "/n/sw/centos6/python-2.7.3/lib/python2.7/urllib2.py", line 378, in _call_chain
    result = func(*args)

  File "/n/sw/centos6/python-2.7.3/lib/python2.7/urllib2.py", line 1207, in http_open
    return self.do_open(httplib.HTTPConnection, req)

  File "/n/sw/centos6/python-2.7.3/lib/python2.7/urllib2.py", line 1177, in do_open
    raise URLError(err)

URLError: <urlopen error [Errno 111] Connection refused>
```
Exception handling should be added to solr_select view and urllib2 should be replaced with requests library.
