### ISSUE TITLE
500 error while accessing /api/v1/analysis/ w/ AnonymousUser

### ISSUE THREAD

**Issue by scottx611x** [parklab/refinery-platform#764]
**Reproduce:**
Hit endpoint: `api/v1/analysis/` as `AnonymousUser`

**Observed:**
```
Traceback (most recent call last):

  File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/tastypie/resources.py", line 202, in wrapper
    response = callback(request, *args, **kwargs)

  File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/tastypie/resources.py", line 440, in dispatch_list
    return self.dispatch('list', request, **kwargs)

  File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/tastypie/resources.py", line 472, in dispatch
    response = method(request, **kwargs)

  File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/tastypie/resources.py", line 1285, in get_list
    bundles.append(self.full_dehydrate(bundle))

  File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/tastypie/resources.py", line 854, in full_dehydrate
    bundle = self.dehydrate(bundle)

  File "/srv/scc/apps/refinery-platform/refinery/core/api.py", line 669, in dehydrate
    if bundle.request.user.userprofile.uuid == bundle.data['owner']:

  File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/django/utils/functional.py", line 205, in inner
    return func(self._wrapped, *args)

AttributeError: 'AnonymousUser' object has no attribute 'userprofile’
```

**Expected:**
No 500 Error

**Comment by scottx611x** [comment]
Merged with #761
