### ISSUE TITLE
Error occuring using `core` management commands

### ISSUE THREAD

**Issue by scottx611x** [parklab/refinery-platform#771]
**Reproduce:**
Run a management command from the `core` app with commit `4c4885e801faeaa2fd2cec02c335425d80fa6f23` checked out.
 Ex: `./manage.py import_workflows`

**Observed:**
```
(refinery-platform)vagrant@refinery:/vagrant/refinery$ ./manage.py import_workflows
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 453, in execute_from_command_line
    utility.execute()
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 272, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 77, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/vagrant/refinery/workflow_manager/management/commands/import_workflows.py", line 6, in <module>
    from core.models import WorkflowEngine
  File "/vagrant/refinery/core/models.py", line 41, in <module>
    from guardian.models import UserObjectPermission
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/guardian/models.py", line 92, in <module>
    monkey_patch_user()
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/guardian/__init__.py", line 24, in monkey_patch_user
    User = get_user_model()
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 127, in get_user_model
    user_model = get_model(app_label, model_name)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/db/models/loading.py", line 230, in get_model
    self._populate()
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/db/models/loading.py", line 75, in _populate
    self.load_app(app_name)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/db/models/loading.py", line 96, in load_app
    models = import_module('.models', app_name)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/vagrant/refinery/analysis_manager/models.py", line 10, in <module>
    from core.models import Analysis
ImportError: cannot import name Analysis
```
**Expected:**
No Error

**Comment by scottx611x** [comment]
Adding the unused import: `from guardian.models import UserObjectPermission` in the error-prone 
command before any imports from `core.models` seems to fix this issue.

![screen shot 2015-11-13 at 4 05 00 pm](https://cloud.githubusercontent.com/assets/5629547/11188466/fadff9a0-8c58-11e5-8f1a-b7c05a1268eb.png)
