### ISSUE TITLE
Galaxy analysis fails with `AttributeError("'tuple' object has no attribute 'lower'",)` in Celeryd

### ISSUE THREAD

**Issue by thinkh** [parklab/refinery-platform#780]
__Reproduce__

1. Install Refinery
2. Install Galaxy and connect it to Refinery with API key
3. Import `refinery_test` tool shed in Galaxy
4. Import test workflows (5-Steps and SPP) to Galaxy
5. Import workflows from Galaxy to Refinery via manage.py script
6. Uploaded the "Request for Comments (RFC) Test" data set
7. Select RFC dataset
8. Switch to Analyze mode
9. Choose 5steps workflow
10. Select only one data file
11. Choose as input dataset "current selection"
12. Launch analysis > "Analysis Launch Successful."
13. Watch the progress...
14. After a few seconds it fails
15. In detail view I get the message "Analysis Test workflow: 5 steps without branching (imported from uploaded file) 2015-11-25@9:36:21 failed. No results were added to your data set."

__Logs__

Galaxy terminal output
```console
192.168.50.50 - - [25/Nov/2015:09:36:27 +0200] "POST /api/libraries?key=ca5fa8a5221e3b3f044afcf68f44cef8 HTTP/1.1" 200 - "-" "python-requests/2.7.0 CPython/2.7.6 Linux/3.13.0-65-generic"
192.168.50.50 - - [25/Nov/2015:09:36:27 +0200] "GET /api/workflows/download/f2db41e1fa331b3e?key=ca5fa8a5221e3b3f044afcf68f44cef8 HTTP/1.1" 200 - "-" "python-requests/2.7.0 CPython/2.7.6 Linux/3.13.0-65-generic"
192.168.50.50 - - [25/Nov/2015:09:36:27 +0200] "POST /api/workflows/upload?key=ca5fa8a5221e3b3f044afcf68f44cef8 HTTP/1.1" 200 - "-" "python-requests/2.7.0 CPython/2.7.6 Linux/3.13.0-65-generic"
192.168.50.50 - - [25/Nov/2015:09:36:27 +0200] "POST /api/histories?key=ca5fa8a5221e3b3f044afcf68f44cef8 HTTP/1.1" 200 - "-" "python-requests/2.7.0 CPython/2.7.6 Linux/3.13.0-65-generic"
192.168.50.50 - - [25/Nov/2015:09:36:31 +0200] "DELETE /api/libraries/1cd8e2f6b131e891?key=ca5fa8a5221e3b3f044afcf68f44cef8 HTTP/1.1" 200 - "-" "python-requests/2.7.0 CPython/2.7.6 Linux/3.13.0-65-generic"
192.168.50.50 - - [25/Nov/2015:09:36:31 +0200] "GET /api/histories/33b43b4e7093c91f?key=ca5fa8a5221e3b3f044afcf68f44cef8 HTTP/1.1" 200 - "-" "python-requests/2.7.0 CPython/2.7.6 Linux/3.13.0-65-generic"
192.168.50.50 - - [25/Nov/2015:09:36:31 +0200] "DELETE /api/workflows/33b43b4e7093c91f?key=ca5fa8a5221e3b3f044afcf68f44cef8 HTTP/1.1" 200 - "-" "python-requests/2.7.0 CPython/2.7.6 Linux/3.13.0-65-generic"
192.168.50.50 - - [25/Nov/2015:09:36:31 +0200] "DELETE /api/histories/33b43b4e7093c91f?key=ca5fa8a5221e3b3f044afcf68f44cef8 HTTP/1.1" 200 - "-" "python-requests/2.7.0 CPython/2.7.6 Linux/3.13.0-65-generic"
```

refinery/log/refinery.log
```log
2015-11-25 03:36:26 DEBUG    analysis_manager.views:389 run() - analysis_manager.views.run called
2015-11-25 03:36:26 DEBUG    core.views:661 get_solr_results() - core.views: get_solr_results
2015-11-25 03:36:26 INFO     requests.packages.urllib3.connectionpool:203 _new_conn() - Starting new HTTP connection (1): 192.168.50.50
2015-11-25 03:36:26 INFO     requests.packages.urllib3.connectionpool:203 _new_conn() - Starting new HTTP connection (1): localhost
2015-11-25 03:36:26 DEBUG    requests.packages.urllib3.connectionpool:383 _make_request() - "GET /solr/data_set_manager/select?sort=Author_Characteristics_2_1_s+asc&fq=%28study_uuid%3A14728e6d-9321-4fd6-9954-730031b2a333+AND+assay_uuid%3A255dfbea-8a1e-4351-a1ac-89d793976802%29&fq=type%3A%28%22Raw+Data+File%22+OR+%22Derived+Data+File%22+OR+%22Array+Data+File%22+OR+%22Derived+Array+Data+File%22+OR+%22Array+Data+Matrix+File%22+OR+%22Derived+Array+Data+Matrix+File%22%29&fq=is_annotation%3Afalse&rows=10000&facet.field=Author_Characteristics_2_1_s&facet.field=REFINERY_ANALYSIS_UUID_2_1_s&facet.field=REFINERY_FILETYPE_2_1_s&facet.field=REFINERY_SUBANALYSIS_2_1_s&facet.field=Year_Characteristics_2_1_s&facet.field=Month_Characteristics_2_1_s&facet.field=REFINERY_TYPE_2_1_s&facet.field=REFINERY_WORKFLOW_OUTPUT_2_1_s&facet.limit=-1&facet.sort=count&facet=false&q=django_ct%3Adata_set_manager.node&start=0&wt=json&facet.pivot=Author_Characteristics_2_1_s%2CMonth_Characteristics_2_1_s&fl=uuid%2Cname%2CAuthor_Characteristics_2_1_s%2CREFINERY_NAME_2_1_s%2CREFINERY_ANALYSIS_UUID_2_1_s%2CREFINERY_FILETYPE_2_1_s%2CREFINERY_SUBANALYSIS_2_1_s%2CTitle_Characteristics_2_1_s%2Cfile_uuid%2CYear_Characteristics_2_1_s%2Cis_annotation%2CMonth_Characteristics_2_1_s%2Cstudy_uuid%2Cassay_uuid%2Ctype%2CREFINERY_TYPE_2_1_s%2CREFINERY_WORKFLOW_OUTPUT_2_1_s HTTP/1.1" 200 None
2015-11-25 03:36:26 DEBUG    requests.packages.urllib3.connectionpool:383 _make_request() - "GET /solr/data_set_manager/select/?q=django_ct:data_set_manager.node&wt=json&start=0&rows=10000&fq=(study_uuid:14728e6d-9321-4fd6-9954-730031b2a333%20AND%20assay_uuid:255dfbea-8a1e-4351-a1ac-89d793976802)&fq=type:(%22Raw%20Data%20File%22%20OR%20%22Derived%20Data%20File%22%20OR%20%22Array%20Data%20File%22%20OR%20%22Derived%20Array%20Data%20File%22%20OR%20%22Array%20Data%20Matrix%20File%22%20OR%20%22Derived%20Array%20Data%20Matrix%20File%22)&fq=is_annotation:false&facet.field=Author_Characteristics_2_1_s&facet.field=REFINERY_ANALYSIS_UUID_2_1_s&facet.field=REFINERY_FILETYPE_2_1_s&facet.field=REFINERY_SUBANALYSIS_2_1_s&facet.field=Year_Characteristics_2_1_s&facet.field=Month_Characteristics_2_1_s&facet.field=REFINERY_TYPE_2_1_s&facet.field=REFINERY_WORKFLOW_OUTPUT_2_1_s&facet.sort=count&facet.limit=-1&facet=false&fl=uuid,name,Author_Characteristics_2_1_s,REFINERY_NAME_2_1_s,REFINERY_ANALYSIS_UUID_2_1_s,REFINERY_FILETYPE_2_1_s,REFINERY_SUBANALYSIS_2_1_s,Title_Characteristics_2_1_s,file_uuid,Year_Characteristics_2_1_s,is_annotation,Month_Characteristics_2_1_s,study_uuid,assay_uuid,type,REFINERY_TYPE_2_1_s,REFINERY_WORKFLOW_OUTPUT_2_1_s&sort=Author_Characteristics_2_1_s%20asc&facet.pivot=Author_Characteristics_2_1_s,Month_Characteristics_2_1_s HTTP/1.1" 200 None
[25/Nov/2015 03:36:26] "GET /solr/data_set_manager/select/?q=django_ct:data_set_manager.node&wt=json&start=0&rows=10000&fq=(study_uuid:14728e6d-9321-4fd6-9954-730031b2a333%20AND%20assay_uuid:255dfbea-8a1e-4351-a1ac-89d793976802)&fq=type:(%22Raw%20Data%20File%22%20OR%20%22Derived%20Data%20File%22%20OR%20%22Array%20Data%20File%22%20OR%20%22Derived%20Array%20Data%20File%22%20OR%20%22Array%20Data%20Matrix%20File%22%20OR%20%22Derived%20Array%20Data%20Matrix%20File%22)&fq=is_annotation:false&facet.field=Author_Characteristics_2_1_s&facet.field=REFINERY_ANALYSIS_UUID_2_1_s&facet.field=REFINERY_FILETYPE_2_1_s&facet.field=REFINERY_SUBANALYSIS_2_1_s&facet.field=Year_Characteristics_2_1_s&facet.field=Month_Characteristics_2_1_s&facet.field=REFINERY_TYPE_2_1_s&facet.field=REFINERY_WORKFLOW_OUTPUT_2_1_s&facet.sort=count&facet.limit=-1&facet=false&fl=uuid,name,Author_Characteristics_2_1_s,REFINERY_NAME_2_1_s,REFINERY_ANALYSIS_UUID_2_1_s,REFINERY_FILETYPE_2_1_s,REFINERY_SUBANALYSIS_2_1_s,Title_Characteristics_2_1_s,file_uuid,Year_Characteristics_2_1_s,is_annotation,Month_Characteristics_2_1_s,study_uuid,assay_uuid,type,REFINERY_TYPE_2_1_s,REFINERY_WORKFLOW_OUTPUT_2_1_s&sort=Author_Characteristics_2_1_s%20asc&facet.pivot=Author_Characteristics_2_1_s,Month_Characteristics_2_1_s HTTP/1.1" 200 8203
2015-11-25 03:36:26 INFO     analysis_manager.views:435 run() - Associating analysis with data set Test 1: Request for Comments (RFC) Test - admin -  (1fce6203-18d9-408f-aac8-2646e3e665d6)
2015-11-25 03:36:26 DEBUG    amqplib:661 _start() - Start from server, version: 8.0, properties: {u'information': u'Licensed under the MPL.  See http://www.rabbitmq.com/', u'product': u'RabbitMQ', u'copyright': u'Copyright (C) 2007-2015 Pivotal Software, Inc.', u'capabilities': {}, u'cluster_name': u'rabbit@refinery', u'platform': u'Erlang/OTP', u'version': u'3.5.6'}, mechanisms: [u'PLAIN', u'AMQPLAIN'], locales: [u'en_US']
2015-11-25 03:36:26 DEBUG    amqplib:507 _open_ok() - Open OK! known_hosts []
2015-11-25 03:36:26 DEBUG    amqplib:70 __init__() - using channel_id: 1
2015-11-25 03:36:26 DEBUG    amqplib:484 _open_ok() - Channel open
2015-11-25 03:36:26 DEBUG    amqplib:90 _do_close() - Closed channel #1
[25/Nov/2015 03:36:26] "POST /analysis_manager/run/ HTTP/1.1" 200 55
```

refinery/log/solr.log
```
2015-11-25 08:36:26.191 INFO  (qtp1329195020-19) [   x:data_set_manager] o.a.s.c.S.Request [data_set_manager] webapp=/solr path=/select params={facet=false&fl=uuid,name,Author_Characteristics_2_1_s,REFINERY_NAME_2_1_s,REFINERY_ANALYSIS_UUID_2_1_s,REFINERY_FILETYPE_2_1_s,REFINERY_SUBANALYSIS_2_1_s,Title_Characteristics_2_1_s,file_uuid,Year_Characteristics_2_1_s,is_annotation,Month_Characteristics_2_1_s,study_uuid,assay_uuid,type,REFINERY_TYPE_2_1_s,REFINERY_WORKFLOW_OUTPUT_2_1_s&sort=Author_Characteristics_2_1_s+asc&start=0&facet.sort=count&q=django_ct:data_set_manager.node&facet.limit=-1&facet.field=Author_Characteristics_2_1_s&facet.field=REFINERY_ANALYSIS_UUID_2_1_s&facet.field=REFINERY_FILETYPE_2_1_s&facet.field=REFINERY_SUBANALYSIS_2_1_s&facet.field=Year_Characteristics_2_1_s&facet.field=Month_Characteristics_2_1_s&facet.field=REFINERY_TYPE_2_1_s&facet.field=REFINERY_WORKFLOW_OUTPUT_2_1_s&wt=json&facet.pivot=Author_Characteristics_2_1_s,Month_Characteristics_2_1_s&fq=(study_uuid:14728e6d-9321-4fd6-9954-730031b2a333+AND+assay_uuid:255dfbea-8a1e-4351-a1ac-89d793976802)&fq=type:("Raw+Data+File"+OR+"Derived+Data+File"+OR+"Array+Data+File"+OR+"Derived+Array+Data+File"+OR+"Array+Data+Matrix+File"+OR+"Derived+Array+Data+Matrix+File")&fq=is_annotation:false&rows=10000} hits=9 status=0 QTime=4 
```

refinery/log/celeryd-w1.log
```
2015-11-25 03:36:26 DEBUG    analysis_manager.tasks:223 run_analysis() - analysis_manager.tasks run_analysis called
2015-11-25 03:36:26 DEBUG    analysis_manager.tasks:253 run_analysis_preprocessing() - analysis_manager.run_analysis_preprocessing called
2015-11-25 03:36:26 DEBUG    workflow_manager.tasks:179 configure_workflow() - workflow.manager configure_workflow called
2015-11-25 03:36:26 DEBUG    workflow_manager.tasks:206 configure_workflow() - workflow_manager.tasks.configure_workflow workflow processing: EXPANSION
2015-11-25 03:36:26 DEBUG    galaxy_connector.galaxy_workflow:94 createStepsAnnot() - galaxy_workflow.createStepsAnnot called
2015-11-25 03:36:27 DEBUG    galaxy_connector.galaxy_workflow:499 countWorkflowSteps() - galaxy_connector.galaxy_workflow countWorkflowSteps called
2015-11-25 03:36:30 DEBUG    analysis_manager.tasks:432 run_analysis_execution() - analysis_manager.run_analysis_execution called
2015-11-25 03:36:30 DEBUG    analysis_manager.tasks:568 import_analysis_in_galaxy() - analysis_manager.tasks import_analysis_in_galaxy called
2015-11-25 03:36:30 ERROR    analysis_manager.tasks:445 run_analysis_execution() - Analysis execution failed: error importing analysis 'Test workflow: 5 steps without branching (imported from uploaded file) 2015-11-25@9:36:21' into Galaxy: Input file with UUID 'fa32c412-5ec7-406d-ac6b-7aa90247e535' is not available
2015-11-25 03:36:37 DEBUG    analysis_manager.tasks:177 chord_postprocessing() - analysis_manager.chord_postprocessing called
```

refinery/log/celeryd-w2.log
```
2015-11-25 03:36:26 DEBUG    file_store:65 import_file() - Importing FileStoreItem with UUID 'fa32c412-5ec7-406d-ac6b-7aa90247e535'
[2015-11-25 03:36:26,979: ERROR/MainProcess] Task file_store.tasks.import_file[bf8409da-e046-4940-85c1-f777f9bb30f6] raised exception: AttributeError("'tuple' object has no attribute 'lower'",)
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/celery/execute/trace.py", line 47, in trace
    return cls(states.SUCCESS, retval=fun(*args, **kwargs))
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/celery/app/task/__init__.py", line 247, in __call__
    return self.run(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/celery/app/__init__.py", line 175, in run
    return fun(*args, **kwargs)
  File "/vagrant/refinery/file_store/tasks.py", line 124, in import_file
    response.headers['Content-Length', file_size])
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
AttributeError: 'tuple' object has no attribute 'lower'
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/celery/execute/trace.py", line 47, in trace
    return cls(states.SUCCESS, retval=fun(*args, **kwargs))
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/celery/app/task/__init__.py", line 247, in __call__
    return self.run(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/celery/app/__init__.py", line 175, in run
    return fun(*args, **kwargs)
  File "/vagrant/refinery/file_store/tasks.py", line 124, in import_file
    response.headers['Content-Length', file_size])
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
AttributeError: 'tuple' object has no attribute 'lower'
2015-11-25 03:36:26 DEBUG    file_store:65 import_file() - Importing FileStoreItem with UUID '78d8447d-0135-4332-b101-85f3851c85da'
[2015-11-25 03:36:27,377: ERROR/MainProcess] Task file_store.tasks.import_file[6fd919e3-94c5-4c98-8440-6f03a7bf6e34] raised exception: AttributeError("'tuple' object has no attribute 'lower'",)
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/celery/execute/trace.py", line 47, in trace
    return cls(states.SUCCESS, retval=fun(*args, **kwargs))
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/celery/app/task/__init__.py", line 247, in __call__
    return self.run(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/celery/app/__init__.py", line 175, in run
    return fun(*args, **kwargs)
  File "/vagrant/refinery/file_store/tasks.py", line 124, in import_file
    response.headers['Content-Length', file_size])
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
AttributeError: 'tuple' object has no attribute 'lower'
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/celery/execute/trace.py", line 47, in trace
    return cls(states.SUCCESS, retval=fun(*args, **kwargs))
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/celery/app/task/__init__.py", line 247, in __call__
    return self.run(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/celery/app/__init__.py", line 175, in run
    return fun(*args, **kwargs)
  File "/vagrant/refinery/file_store/tasks.py", line 124, in import_file
    response.headers['Content-Length', file_size])
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
AttributeError: 'tuple' object has no attribute 'lower'
2015-11-25 03:36:27 DEBUG    file_store:65 import_file() - Importing FileStoreItem with UUID 'd463b4f1-01a6-46aa-b8c7-09c3c5f29d3b'
[2015-11-25 03:36:27,796: ERROR/MainProcess] Task file_store.tasks.import_file[bf0473de-dfe2-435b-b826-54b357703b15] raised exception: AttributeError("'tuple' object has no attribute 'lower'",)
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/celery/execute/trace.py", line 47, in trace
    return cls(states.SUCCESS, retval=fun(*args, **kwargs))
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/celery/app/task/__init__.py", line 247, in __call__
    return self.run(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/celery/app/__init__.py", line 175, in run
    return fun(*args, **kwargs)
  File "/vagrant/refinery/file_store/tasks.py", line 124, in import_file
    response.headers['Content-Length', file_size])
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
AttributeError: 'tuple' object has no attribute 'lower'
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/celery/execute/trace.py", line 47, in trace
    return cls(states.SUCCESS, retval=fun(*args, **kwargs))
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/celery/app/task/__init__.py", line 247, in __call__
    return self.run(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/celery/app/__init__.py", line 175, in run
    return fun(*args, **kwargs)
  File "/vagrant/refinery/file_store/tasks.py", line 124, in import_file
    response.headers['Content-Length', file_size])
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
AttributeError: 'tuple' object has no attribute 'lower'
2015-11-25 03:36:27 DEBUG    file_store:65 import_file() - Importing FileStoreItem with UUID 'a4007c6c-91a5-4e11-be7b-d0b2523b9248'
[2015-11-25 03:36:28,206: ERROR/MainProcess] Task file_store.tasks.import_file[ed35a8d8-6bc6-4209-a6a4-e930047d75cb] raised exception: AttributeError("'tuple' object has no attribute 'lower'",)
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/celery/execute/trace.py", line 47, in trace
    return cls(states.SUCCESS, retval=fun(*args, **kwargs))
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/celery/app/task/__init__.py", line 247, in __call__
    return self.run(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/celery/app/__init__.py", line 175, in run
    return fun(*args, **kwargs)
  File "/vagrant/refinery/file_store/tasks.py", line 124, in import_file
    response.headers['Content-Length', file_size])
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
AttributeError: 'tuple' object has no attribute 'lower'
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/celery/execute/trace.py", line 47, in trace
    return cls(states.SUCCESS, retval=fun(*args, **kwargs))
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/celery/app/task/__init__.py", line 247, in __call__
    return self.run(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/celery/app/__init__.py", line 175, in run
    return fun(*args, **kwargs)
  File "/vagrant/refinery/file_store/tasks.py", line 124, in import_file
    response.headers['Content-Length', file_size])
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
AttributeError: 'tuple' object has no attribute 'lower'
2015-11-25 03:36:28 DEBUG    file_store:65 import_file() - Importing FileStoreItem with UUID '21e699b9-e95e-4497-831e-8f6749e2071f'
[2015-11-25 03:36:28,595: ERROR/MainProcess] Task file_store.tasks.import_file[6a455b7d-8772-4c4f-8917-890d27f25e54] raised exception: AttributeError("'tuple' object has no attribute 'lower'",)
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/celery/execute/trace.py", line 47, in trace
    return cls(states.SUCCESS, retval=fun(*args, **kwargs))
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/celery/app/task/__init__.py", line 247, in __call__
    return self.run(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/celery/app/__init__.py", line 175, in run
    return fun(*args, **kwargs)
  File "/vagrant/refinery/file_store/tasks.py", line 124, in import_file
    response.headers['Content-Length', file_size])
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
AttributeError: 'tuple' object has no attribute 'lower'
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/celery/execute/trace.py", line 47, in trace
    return cls(states.SUCCESS, retval=fun(*args, **kwargs))
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/celery/app/task/__init__.py", line 247, in __call__
    return self.run(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/celery/app/__init__.py", line 175, in run
    return fun(*args, **kwargs)
  File "/vagrant/refinery/file_store/tasks.py", line 124, in import_file
    response.headers['Content-Length', file_size])
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
AttributeError: 'tuple' object has no attribute 'lower'
2015-11-25 03:36:28 DEBUG    file_store:65 import_file() - Importing FileStoreItem with UUID 'bb2205d7-25bd-4810-9488-fc9ea60be62e'
[2015-11-25 03:36:28,983: ERROR/MainProcess] Task file_store.tasks.import_file[85653b95-0af8-4cc8-bfb1-88ecd2a44c47] raised exception: AttributeError("'tuple' object has no attribute 'lower'",)
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/celery/execute/trace.py", line 47, in trace
    return cls(states.SUCCESS, retval=fun(*args, **kwargs))
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/celery/app/task/__init__.py", line 247, in __call__
    return self.run(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/celery/app/__init__.py", line 175, in run
    return fun(*args, **kwargs)
  File "/vagrant/refinery/file_store/tasks.py", line 124, in import_file
    response.headers['Content-Length', file_size])
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
AttributeError: 'tuple' object has no attribute 'lower'
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/celery/execute/trace.py", line 47, in trace
    return cls(states.SUCCESS, retval=fun(*args, **kwargs))
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/celery/app/task/__init__.py", line 247, in __call__
    return self.run(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/celery/app/__init__.py", line 175, in run
    return fun(*args, **kwargs)
  File "/vagrant/refinery/file_store/tasks.py", line 124, in import_file
    response.headers['Content-Length', file_size])
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
AttributeError: 'tuple' object has no attribute 'lower'
2015-11-25 03:36:28 DEBUG    file_store:65 import_file() - Importing FileStoreItem with UUID 'd42d93f3-5e06-40ca-a983-e54339be4e9b'
[2015-11-25 03:36:29,370: ERROR/MainProcess] Task file_store.tasks.import_file[fe3d0996-f7a3-4096-8cf6-493b32d5920f] raised exception: AttributeError("'tuple' object has no attribute 'lower'",)
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/celery/execute/trace.py", line 47, in trace
    return cls(states.SUCCESS, retval=fun(*args, **kwargs))
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/celery/app/task/__init__.py", line 247, in __call__
    return self.run(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/celery/app/__init__.py", line 175, in run
    return fun(*args, **kwargs)
  File "/vagrant/refinery/file_store/tasks.py", line 124, in import_file
    response.headers['Content-Length', file_size])
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
AttributeError: 'tuple' object has no attribute 'lower'
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/celery/execute/trace.py", line 47, in trace
    return cls(states.SUCCESS, retval=fun(*args, **kwargs))
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/celery/app/task/__init__.py", line 247, in __call__
    return self.run(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/celery/app/__init__.py", line 175, in run
    return fun(*args, **kwargs)
  File "/vagrant/refinery/file_store/tasks.py", line 124, in import_file
    response.headers['Content-Length', file_size])
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
AttributeError: 'tuple' object has no attribute 'lower'
2015-11-25 03:36:29 DEBUG    file_store:65 import_file() - Importing FileStoreItem with UUID '03dd9cad-5cf6-4603-a6f6-dff9266a6e6e'
[2015-11-25 03:36:29,763: ERROR/MainProcess] Task file_store.tasks.import_file[f489fae6-8017-495b-bfb3-5314bf5bc65f] raised exception: AttributeError("'tuple' object has no attribute 'lower'",)
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/celery/execute/trace.py", line 47, in trace
    return cls(states.SUCCESS, retval=fun(*args, **kwargs))
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/celery/app/task/__init__.py", line 247, in __call__
    return self.run(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/celery/app/__init__.py", line 175, in run
    return fun(*args, **kwargs)
  File "/vagrant/refinery/file_store/tasks.py", line 124, in import_file
    response.headers['Content-Length', file_size])
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
AttributeError: 'tuple' object has no attribute 'lower'
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/celery/execute/trace.py", line 47, in trace
    return cls(states.SUCCESS, retval=fun(*args, **kwargs))
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/celery/app/task/__init__.py", line 247, in __call__
    return self.run(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/celery/app/__init__.py", line 175, in run
    return fun(*args, **kwargs)
  File "/vagrant/refinery/file_store/tasks.py", line 124, in import_file
    response.headers['Content-Length', file_size])
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
AttributeError: 'tuple' object has no attribute 'lower'
```

__Expected__

Analysis should be executed successfully.

**Comment by thinkh** [comment]
It seems that the most interesting log is celeryd-w2.log, where the errors with traceback are logged: raised exception: AttributeError("'tuple' object has no attribute 'lower'",)`. Please have a detailed look there.

**Comment by ngehlenborg** [comment]
Can you check if the files from the RFC data set were imported? Do you see the content of the file that you tried to run through the workflow when you click the arrow/download link in the data set browser? What is the URL shown for those files?

**Comment by thinkh** [comment]
> Can you check if the files from the RFC data set were imported?

I'm not sure where/how to look this up? When I select the dataset from the startpage, I get the following screen.

![Data Set Test 1: Request for Comments (RFC) Test](https://cloud.githubusercontent.com/assets/5851088/11447551/e6113bea-9547-11e5-850d-cc31b5bc3ac4.png)

> Do you see the content of the file that you tried to run through the workflow when you click the arrow/download link in the data set browser? 

When I select the executed workflow from the startpage, I get this screen:

![Executed, but failed workflow](https://cloud.githubusercontent.com/assets/5851088/11447593/d1e566ea-9548-11e5-8990-7047d845c3d1.png)

> What is the URL shown for those files?

Same as the one listed in the assay file, pointing to your server. I can download the files to my PC by clicking the icon (means they are available at the remote server).

[a_assay.txt](https://github.com/parklab/refinery-platform/files/46110/a_assay.txt)
