### ISSUE TITLE
Fix Neo4j errors in unit tests

### ISSUE THREAD

**Issue by hackdna** [parklab/refinery-platform#794]
From Travis CI build log:
```
$ python manage.py test analysis_manager
Creating test database for alias 'default'...
2015-12-01 15:50:03 INFO     core.utils:116 add_read_access_in_neo4j() - Adding read access for users ([-1]) to data sets ([]) in Neo4J
2015-12-01 15:50:03 INFO     httpstream:310 send() - > GET http://localhost:7474/db/data/
2015-12-01 15:50:03 DEBUG    httpstream:316 send() - > Host: localhost:7474
2015-12-01 15:50:03 DEBUG    httpstream:316 send() - > X-Stream: true
2015-12-01 15:50:03 DEBUG    httpstream:316 send() - > User-Agent: py2neo/2.0.7 HTTPStream/1.5.0 Python/2.7.9-final-0 (linux2)
2015-12-01 15:50:03 ERROR    httpstream:168 __init__() - ! SocketError: Connection refused
Traceback (most recent call last):
  File "/opt/python/2.7.9/lib/python2.7/logging/__init__.py", line 859, in emit
    msg = self.format(record)
  File "/opt/python/2.7.9/lib/python2.7/logging/__init__.py", line 732, in format
    return fmt.format(record)
  File "/opt/python/2.7.9/lib/python2.7/logging/__init__.py", line 471, in format
    record.message = record.getMessage()
  File "/opt/python/2.7.9/lib/python2.7/logging/__init__.py", line 335, in getMessage
    msg = msg % self.args
TypeError: not enough arguments for format string
Logged from file utils.py, line 144
```

Need to rewrite logger calls in the following try-catch blocks to make sure all variables are provided for string formatting:
https://github.com/parklab/refinery-platform/blob/develop/refinery/core/utils.py#L127
https://github.com/parklab/refinery-platform/blob/develop/refinery/core/utils.py#L165
Note: cannot simply add `dataset_uuid` because it might be referenced before assignment

**Comment by hackdna** [comment]
Simply adding `dataset_uuid` doesn't address the issue properly because this variable might be referenced before assignment.

**Comment by flekschas** [comment]
Can you please give a precise example when the current implementation fails?

According to Travis CI there were no problem: https://travis-ci.org/parklab/refinery-platform/builds/94511580. All tests passed locally and on Travis CI. The only issue is that Travis CI's Neo4J seems to be useless:

```
2015-12-02 17:21:30 ERROR    core.utils:144 add_read_access_in_neo4j() - Failed to add read access for users ([-1]) to data sets (uuids: []) to Neo4J. Exception: Transaction support not available from this Neo4j server version
```
