### ISSUE TITLE
Impossible to create input file mapping

### ISSUE THREAD

**Issue by hackdna** [parklab/refinery-platform#910]
Commit 9ffd03e

## Steps to reproduce
1. Run Refinery in `dev` or `prod` mode (e.g., `fab vm conf:dev`)
1. Open a data set and click on the Analyze tab
1. Select a workflow that requires two inputs
1. Click New... button to create a new file input mapping

## Observed results
Nothing changes on screen and the following error message is displayed in the browser console:
```
Error: [$injector:unpr] http://errors.angularjs.org/1.4.9/$injector/unpr?p0=aProvider%20%3C-%20a
    at Error (native)
    at http://192.168.50.50:8000/static/vendor/angular/angular.min.js:6:416
    at http://192.168.50.50:8000/static/vendor/angular/angular.min.js:41:144
    at Object.d [as get] (http://192.168.50.50:8000/static/vendor/angular/angular.min.js:39:129)
    at http://192.168.50.50:8000/static/vendor/angular/angular.min.js:41:218
    at d (http://192.168.50.50:8000/static/vendor/angular/angular.min.js:39:129)
    at e (http://192.168.50.50:8000/static/vendor/angular/angular.min.js:39:399)
    at Object.instantiate (http://192.168.50.50:8000/static/vendor/angular/angular.min.js:40:37)
    at http://192.168.50.50:8000/static/vendor/angular/angular.min.js:80:442
    at http://192.168.50.50:8000/static/vendor/angular-bootstrap/ui-bootstrap-tpls.min.js:9:29229(anonymous function) @ angular.js:12722(anonymous function) @ angular.js:9490(anonymous function) @ angular.js:14999r.$eval @ angular.js:16251r.$digest @ angular.js:16069r.$apply @ angular.js:16359g @ angular.js:10791R @ angular.js:10989v.onload @ angular.js:10930
angular.js:10967 XHR finished loading: GET "http://192.168.50.50:8000/api/v1/analysis/?data_set__uuid=aeff8005-68b4-4fa7-ba69-f355220d92f8&format=json&limit=0&order_by=-time_start&status=RUNNING".(anonymous function) @ angular.js:10967r @ angular.js:10760g @ angular.js:10470(anonymous function) @ angular.js:14991r.$eval @ angular.js:16251r.$digest @ angular.js:16069r.$apply @ angular.js:16359(anonymous function) @ angular.js:18141e @ angular.js:5729(anonymous function) @ angular.js:6006
```

## Expected results
1. A new file input mapping dialog box should be displayed
1. No error should be logged in the browser console

## Notes
This does not occur in `gdev` mode.

**Comment by ngehlenborg** [comment]
Probably an annotation issue - @flekschas talk to @ngehlenborg.

**Comment by flekschas** [comment]
Probably files `node-mapping.js` and `node-relationship.js`.

**Comment by hackdna** [comment]
Commit 9ecdbf5b. Error when selecting a workflow:
```
2016-03-21 12:37:03 ERROR    django.request:224 handle_uncaught_exception() - Internal Server Error: /api/v1/noderelationship
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 88, in get_response
    response = middleware_method(request)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/middleware/common.py", line 81, in process_request
    "settings.") % (new_url[0], new_url[1]))
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 192.168.50.50:8000/api/v1/noderelationship/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
Internal Server Error: /api/v1/noderelationship
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 88, in get_response
    response = middleware_method(request)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/middleware/common.py", line 81, in process_request
    "settings.") % (new_url[0], new_url[1]))
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 192.168.50.50:8000/api/v1/noderelationship/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
2016-03-21 12:37:03 ERROR    django.request:224 handle_uncaught_exception() - Internal Server Error: /api/v1/noderelationship
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 88, in get_response
    response = middleware_method(request)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/middleware/common.py", line 81, in process_request
    "settings.") % (new_url[0], new_url[1]))
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 192.168.50.50:8000/api/v1/noderelationship/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
```

Error when clicking on "New" button to create an input mapping:
```
ReferenceError: InputDialogInstanceController is not defined
    at r.NodeRelationshipListCtrl.$scope.openNewMappingDialog (http://192.168.50.50:8000/static/js/node-relationship.js:186:19)
    at fn (eval at <anonymous> (http://192.168.50.50:8000/static/vendor/angular/angular.min.js:216:110), <anonymous>:4:251)
    at e (http://192.168.50.50:8000/static/vendor/angular/angular.min.js:257:177)
    at r.$eval (http://192.168.50.50:8000/static/vendor/angular/angular.min.js:133:446)
    at r.$apply (http://192.168.50.50:8000/static/vendor/angular/angular.min.js:134:175)
    at HTMLAnchorElement.<anonymous> (http://192.168.50.50:8000/static/vendor/angular/angular.min.js:257:229)
    at HTMLAnchorElement.n.event.dispatch (http://192.168.50.50:8000/static/vendor/jquery/dist/jquery.min.js:3:6404)
    at HTMLAnchorElement.r.handle (http://192.168.50.50:8000/static/vendor/jquery/dist/jquery.min.js:3:3179)
```

**Comment by flekschas** [comment]
@hackdna Lets separate these issues. The second one is related to the UI and the client-side code while the first one is clearly unrelated.
@scottx611x Could you look into the first issue.

**Comment by scottx611x** [comment]
@flekschas sure! Can probably get around to that a bit later tonight.

**Comment by flekschas** [comment]
@scottx611x Cool thanks. Does the re-assignment cycle mean you're done? :) Just asking if I should close the issue once I am done or assign it to you?

**Comment by scottx611x** [comment]
@flekschas nope! reassignment was a mistake on my end sorry :)

**Comment by flekschas** [comment]
Python part now outsourced to #978.
