### ISSUE TITLE
Node mapping related issue

### ISSUE THREAD

**Issue by flekschas** [parklab/refinery-platform#978]
Commit 9ecdbf5b. Error when selecting a workflow:
```
2016-03-21 12:37:03 ERROR    django.request:224 handle_uncaught_exception() - Internal Server Error: /api/v1/noderelationship
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 88, in get_response
    response = middleware_method(request)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/middleware/common.py", line 81, in process_request
    "settings.") % (new_url[0], new_url[1]))
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 192.168.50.50:8000/api/v1/noderelationship/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
Internal Server Error: /api/v1/noderelationship
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 88, in get_response
    response = middleware_method(request)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/middleware/common.py", line 81, in process_request
    "settings.") % (new_url[0], new_url[1]))
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 192.168.50.50:8000/api/v1/noderelationship/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
2016-03-21 12:37:03 ERROR    django.request:224 handle_uncaught_exception() - Internal Server Error: /api/v1/noderelationship
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 88, in get_response
    response = middleware_method(request)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/middleware/common.py", line 81, in process_request
    "settings.") % (new_url[0], new_url[1]))
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 192.168.50.50:8000/api/v1/noderelationship/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
```

**Comment by flekschas** [comment]
See #910.
