### ISSUE TITLE
Handle Gateway Time-Out error during analysis

### ISSUE THREAD

**Issue by hackdna** [parklab/refinery-platform#992]
Relevant log entries:
```
2016-03-04 16:42:25 ERROR    analysis_manager.tasks:233 import_analysis_in_galaxy() - Failed adding file 'f14d0205-4959-41d8-8ffa-4e9e9cf9c736' to Galaxy library '417e33144b294c21': HTTP Error 504: Gateway Time-out
[2016-03-04 16:42:25,862: ERROR/MainProcess] Task analysis_manager.tasks.start_galaxy_analysis[3f8a009e-39ed-445f-93a0-a500e0661c1d] raised unexpected: IOError()
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/ubuntu/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/srv/refinery-platform/refinery/analysis_manager/tasks.py", line 266, in start_galaxy_analysis
    ret_list, analysis.library_id, connection)
  File "/srv/refinery-platform/refinery/analysis_manager/tasks.py", line 229, in import_analysis_in_galaxy
    library_id, file_path)[0]['id']
  File "/home/ubuntu/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/bioblend/galaxy/libraries/__init__.py", line 251, in upload_file_from_local_path
    return self._do_upload(**vars)
  File "/home/ubuntu/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/bioblend/galaxy/libraries/__init__.py", line 217, in _do_upload
    files_attached=files_attached)
  File "/home/ubuntu/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/bioblend/galaxy/client.py", line 182, in _post
    r = self.gi.make_post_request(url, payload=payload, files_attached=files_attached)
  File "/home/ubuntu/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/bioblend/galaxyclient.py", line 85, in make_post_request
    fp = urllib2.urlopen(request)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError
```

**Comment by hackdna** [comment]
In addition, a gateway time-out can occur during large file uploads.
Celery log:
```
2016-04-20 17:33:52 ERROR    analysis_manager.tasks:268 start_galaxy_analysis() - Analysis execution in Galaxy failed: error importing analysis 'FastQC 2016-4-20@17:17:48' into Galaxy: Failed to add file 'fbaeadf0-4583-47cc-bf89-e00829efcccf' to Galaxy library 'f597429621d6eb2b': HTTP Error 504: Gateway Time-out
```
Galaxy log:
```
134.174.183.88 - - [20/Apr/2016:21:32:52 +0000] "POST /api/libraries/f597429621d6eb2b/contents HTTP/1.0" 500 - "-" "Python-urllib/2.7"
Error - <class 'webob.request.DisconnectionError'>: The client disconnected while sending the POST/PUT body (2481357855 more bytes were expected)
URL: http://galaxy-dev.aws.stemcellcommons.org/api/libraries/f597429621d6eb2b/contents
File '/mnt/galaxy/galaxy-app/lib/galaxy/web/framework/middleware/error.py', line 151 in __call__
  app_iter = self.application(environ, sr_checker)
File '/mnt/galaxy/galaxy-app/.venv/local/lib/python2.7/site-packages/paste/recursive.py', line 85 in __call__
  return self.application(environ, start_response)
File '/mnt/galaxy/galaxy-app/.venv/local/lib/python2.7/site-packages/paste/httpexceptions.py', line 640 in __call__
  return self.application(environ, start_response)
File '/mnt/galaxy/galaxy-app/lib/galaxy/web/framework/base.py', line 126 in __call__
  return self.handle_request( environ, start_response )
File '/mnt/galaxy/galaxy-app/lib/galaxy/web/framework/base.py', line 153 in handle_request
  trans = self.transaction_factory( environ )
File '/mnt/galaxy/galaxy-app/lib/galaxy/web/framework/webapp.py', line 66 in <lambda>
  self.set_transaction_factory( lambda e: self.transaction_chooser( e, galaxy_app, session_cookie ) )
File '/mnt/galaxy/galaxy-app/lib/galaxy/web/framework/webapp.py', line 97 in transaction_chooser
  return GalaxyWebTransaction( environ, galaxy_app, self, session_cookie )
File '/mnt/galaxy/galaxy-app/lib/galaxy/web/framework/webapp.py', line 193 in __init__
  self.error_message = self._authenticate_api( session_cookie )
File '/mnt/galaxy/galaxy-app/lib/galaxy/web/framework/webapp.py', line 308 in _authenticate_api
  api_key = self.request.params.get('key', None)
File '/mnt/galaxy/galaxy-app/.venv/local/lib/python2.7/site-packages/webob/request.py', line 853 in params
  params = NestedMultiDict(self.GET, self.POST)
File '/mnt/galaxy/galaxy-app/.venv/local/lib/python2.7/site-packages/webob/request.py', line 789 in POST
  self.make_body_seekable()
File '/mnt/galaxy/galaxy-app/.venv/local/lib/python2.7/site-packages/webob/request.py', line 943 in make_body_seekable
  self.copy_body()
File '/mnt/galaxy/galaxy-app/.venv/local/lib/python2.7/site-packages/webob/request.py', line 963 in copy_body
  did_copy = self._copy_body_tempfile()
File '/mnt/galaxy/galaxy-app/.venv/local/lib/python2.7/site-packages/webob/request.py', line 980 in _copy_body_tempfile
  data = input.read(min(todo, 65536))
File '/mnt/galaxy/galaxy-app/.venv/local/lib/python2.7/site-packages/webob/request.py', line 1549 in readinto
  + "(%d more bytes were expected)" % self.remaining
DisconnectionError: The client disconnected while sending the POST/PUT body (2481357855 more bytes were expected)


CGI Variables
-------------
  CONTENT_LENGTH: '4628837407'
  CONTENT_TYPE: 'multipart/form-data; boundary=f983be6e59a24540b6fc84e3d8be69b2'
  HTTP_ACCEPT_ENCODING: 'identity'
  HTTP_CONNECTION: 'close'
  HTTP_HOST: 'galaxy-dev.aws.stemcellcommons.org'
  HTTP_USER_AGENT: 'Python-urllib/2.7'
  HTTP_X_FORWARDED_FOR: '134.174.183.88'
  HTTP_X_FORWARDED_HOST: 'galaxy-dev.aws.stemcellcommons.org'
  ORGINAL_HTTP_HOST: 'galaxy_app'
  ORGINAL_REMOTE_ADDR: '127.0.0.1'
  PATH_INFO: '/api/libraries/f597429621d6eb2b/contents'
  REMOTE_ADDR: '134.174.183.88'
  REQUEST_METHOD: 'POST'
  SERVER_NAME: '127.0.0.1'
  SERVER_PORT: '8080'
  SERVER_PROTOCOL: 'HTTP/1.0'


WSGI Variables
--------------
  application: <paste.recursive.RecursiveMiddleware object at 0x7fcce108fcd0>
  is_api_request: True
  paste.expected_exceptions: [<class 'paste.httpexceptions.HTTPException'>]
  paste.httpexceptions: <paste.httpexceptions.HTTPExceptionHandler object at 0x7fcce108fc50>
  paste.httpserver.proxy.host: 'dummy'
  paste.httpserver.proxy.scheme: 'http'
  paste.httpserver.thread_pool: <paste.httpserver.ThreadPool object at 0x7fcce0aabb90>
  paste.recursive.forward: <paste.recursive.Forwarder from />
  paste.recursive.include: <paste.recursive.Includer from />
  paste.recursive.include_app_iter: <paste.recursive.IncluderAppIter from />
  paste.recursive.script_name: ''
  paste.throw_errors: True
  request_id: '7015ac7c073f11e6a8a60a4d98d6c597'
  webob._body_file: (<_io.BufferedReader>, <socket._fileobject object at 0x7fccc41ca6d0 length=4628837407>)
  webob._parsed_query_vars: (GET([]), '')
  wsgi process: 'Multithreaded'
```

**Comment by hackdna** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;0dqHQzfq&#x2F;34-deploy-scc-release-on-aws"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> deploy SCC release on AWS</a>

**Comment by ngehlenborg** [comment]
This is related to #999.

**Comment by mccalluc** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;SmNwQPCV&#x2F;43-992"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> #992</a>
